### ISSUE TITLE
Global Menu not working

### ISSUE THREAD

**Issue by baddwin** [ZaWertun/fedora-copr-kde5#1]
Does global menu widget work on your side?

**Comment by g6avk** [comment]
Works here, tested the widget and also the menu on a new panel.

**Comment by ZaWertun** [comment]
It works for me at least with Dolphin, Google Chrome and Okular, just checked it.

Could you be more specific?
There is bunch of bugs on KDE bugzilla related to the global menu (one with Krita, another one with Wayland and some others).
You can check here: [bugs.kde.org - quicksearch "global menu"](https://bugs.kde.org/buglist.cgi?quicksearch=global%20menu&list_id=1631469).

**Comment by baddwin** [comment]
I have just system-upgrade from 29 to 30. Then I add your copr repo to update KF5. Soon after rebooting, the global menu doesn't show up menu list. But the menu is displayed in every app instead.
Is there an additional config in Systemsettings to set? As I got a touchpad scroll setting to be reset to default after the upgrade.
