### ISSUE TITLE
Update kde-connect

### ISSUE THREAD

**Issue by bugzy** [ZaWertun/fedora-copr-kde5#10]
Current kde-connect package is at 1.3.5, but packaged version is 1.3.4. See https://invent.kde.org/kde/kdeconnect-kde/-/tags/v1.3.5 and https://github.com/KDE/kdeconnect-kde/releases 
Thanks

**Comment by ZaWertun** [comment]
e23318ba53696453e236840849f778e6a418bde0

**Comment by ZaWertun** [comment]
Copr build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1042735/

**Comment by ZaWertun** [comment]
Done.

**Comment by bugzy** [comment]
Excellent. Thanks
