### ISSUE TITLE
Black screen and blinking cursor after logging out of the session

### ISSUE THREAD

**Issue by carabao72** [ZaWertun/fedora-copr-kde5#100]
Hello,

I get a blinking cursor and a black screen after logging out of my session. 

Problem with SDDM? 

```
rpm -q sddm
sddm-0.19.0-18.fc35.x86_64
```

/etc/sddm.conf.d/kde-settings.conf
```
[Autologin]
Relogin=false
Session=
User=

[General]
HaltCommand=/usr/bin/systemctl poweroff
Numlock=on
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=breeze
CursorTheme=breeze_cursors
Font=Noto Sans,10,-1,5,50,0,0,0,0,0

[Users]
MaximumUid=60000
MinimumUid=1000

```

My xsession-errors file is empty

If I have to bring you some information, don’t hesitate to ask me, I will try to do my best to help you.

Thank You

**Comment by g6avk** [comment]
FWIW, I see this from time to time and I have to drop to a shell and init 3/5 to get back to SDDM
Today whilst testing X and Wayland (I'm running an nVida card) logging out worked about 95% of the time. However some days logging out (from X which I normally use) never works. 
There was an issue with it being kde-connect but am not sure if that was fixed and have not got around to testing.

Regarding xsession-errors being empty, I don't think that is used now..

**Comment by carabao72** [comment]
hello,

The problem seems to have disappeared. It is true that I have cut a few programs that I no longer needed. Thinking about it, I wonder if the problem didn’t appear after installing clamAV? In any case, since I deleted this one, the disconnection seems to work. Possible, coincidence? Or is it the removal of some unused files from gnome?

**Comment by g6avk** [comment]
I have not seen this for a very longtime now (I'm still using Xorg) maybe this can be closed?

**Comment by ZaWertun** [comment]
Sure.

**Comment by g6avk** [comment]
Ah.. I was not the OP so cannot close it.
