### ISSUE TITLE
5.24.2 & multi-monitor regression; fix available in merge request

### ISSUE THREAD

**Issue by r2rX** [ZaWertun/fedora-copr-kde5#102]
Hello there,

As of 5.24, there has been a regression with multi-monitor use. After submitting a bug report, there seems to be a fix available that's queued in the projects merge request: https://invent.kde.org/plasma/kwin/-/merge_requests/2066

This should be incorporated in 5.24.3 but I was curious...is it possible to incorporate this fix and recompile the necessary component/s for 5.24.2?

Thanks.

**Comment by ZaWertun** [comment]
I've tried to apply patch to kwin-5.24.2 - no luck, it's needs rebase to apply cleanly.

**Comment by r2rX** [comment]
Understood. Thanks for trying.
