### ISSUE TITLE
Cannot upgrade kalendar

### ISSUE THREAD

**Issue by LPW00** [ZaWertun/fedora-copr-kde5#103]
Error: Transaction test error:
  file /usr/bin/kalendarac from install of kalendar-1.0.0-2.fc35.x86_64 conflicts with file from package kalendar-reminder-daemon-1.0.0-1.fc35.x86_64

I guess kalendar-reminder-daemon needs an update.

**Comment by ZaWertun** [comment]
Hello.
This issue was fixed in kalendar-1.0.0-2, but I've forgot to regenerate repo metadata.
I'll do it now.

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/3578243/

**Comment by LPW00** [comment]
Thank you!
