### ISSUE TITLE
HEIF/HEIC and JPEG XL support in KImageFormats (attempt 2)

### ISSUE THREAD

**Issue by Quppa** [ZaWertun/fedora-copr-kde5#104]
I was hoping to try again at enabling HEIF/HEIC support in KImageFormats, and to enable JPEG XL support also.

I think the previous attempt (#91) didn't work because `libheif` isn't in the official Fedora repositories, only RPM Fusion. Can the COPR build be made to reference it?

`libjxl`, on the other hand, [is available](https://fedora.pkgs.org/35/fedora-updates-x86_64/libjxl-0.6.1-6.fc35.x86_64.rpm.html), so I'm hopeful `-DKIMAGEFORMATS_JXL=ON` will just work.

**Comment by ZaWertun** [comment]
With new build of `kio-extras` (`kio-extras-21.12.3-1.fc35.x86_64`) and if you have enabled RPMFusion repo - you should get HEIF image support.
`kio-extras` now depends (soft depend) on `qt-heif-image-plugin` package.
It works for me in Dolphin (previews) and in Gwenview.

**Comment by ZaWertun** [comment]
Also this build needed to have JPEG JXL previews: https://copr.fedorainfracloud.org/coprs/build/3598561.

**Comment by ZaWertun** [comment]
Gwenview build with JPEG XL added to supported MIME types: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/3598569/.

**Comment by Quppa** [comment]
Excellent, it's all working. Thank you.
