### ISSUE TITLE
Fedora updates wants to replace your repo's kwin*

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#105]
Hi,

Nothing major..
Fedora updates wants to replace your Kwin. This box has win-5.24.2-1.fc35.x86_64 and Fedora updates 
has 5.24.2-2. Version bump needed maybe?

**Comment by ZaWertun** [comment]
This Fedora build includes new upstream patch, I'll merge it & rebuild package.

**Comment by ZaWertun** [comment]
Build: https://copr.fedorainfracloud.org/coprs/build/3633833.

**Comment by g6avk** [comment]
Thanks for the fast fix 👍🏻
