### ISSUE TITLE
Fedora updates wants to replace your Kwin and others again

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#106]
Nothing major..
Fedora updates wants to replace your Kwin again + some plasma files:  
plasma-integration, plasma-nm*, xdg-desktop-portal-kde etc

**Comment by g6avk** [comment]
Did you bump kwin* as well?
On this F35 box the kwin* updates are 5.24.3-2 which is from fedora-updates repo

**Comment by ZaWertun** [comment]
You're right, I've submitted new build just now.

**Comment by g6avk** [comment]
Thanks for the quick fix 👍🏻 

FYI I have just seen another one with kwayland-integration in "updates" 5.24.3-2 I think you also provide that?

**Comment by g6avk** [comment]
Thanks again for the new build 👍🏻
