### ISSUE TITLE
Sticky notes in taskbar broken frameworks 5.93

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#107]
Just updated to 5.93 and find the sticky notes widget is broken.

I have it in my taskbar (to use it as a note pad) and it raises when I click on it and I can enter text.
After the update it and clicking on it only a tiny square appears.

I downgraded just the kf5-plasma package and that fixes it for me.
Note: With 5.93 it works as it should on the Desktop but not when it is placed in the Taskbar.

So far nothing found yet in kde.bugs Can anyone confirm this?

**Comment by ZaWertun** [comment]
> Just updated to 5.93 and find the sticky notes widget is broken.
> 
> I have it in my taskbar (to use it as a note pad) and it raises when I click on it and I can enter text. After the update it and clicking on it only a tiny square appears.
> 
> I downgraded just the kf5-plasma package and that fixes it for me. Note: With 5.93 it works as it should on the Desktop but not when it is placed in the Taskbar.
> 
> So far nothing found yet in kde.bugs Can anyone confirm this?

Yep, I've got same issue after update.
Looks like it's caused by this change:
> ### Plasma Framework
> Do not compute sizes within dialogs when they’re not visible
> https://kde.org/announcements/frameworks/5/5.93.0/#plasma-framework

But I'm not sure.

![изображение](https://user-images.githubusercontent.com/1080298/162713871-bf9ee9ff-0b7e-482d-8e38-577d7f21a5ea.png)

**Comment by ZaWertun** [comment]
Confirmed - reverting commit https://invent.kde.org/frameworks/plasma-framework/-/commit/29d31c159503e454b3c483b0b7eb180ce0ee926a fixes this issue.

**Comment by ZaWertun** [comment]
Could you create issue, please?

**Comment by g6avk** [comment]
> Could you create issue, please?

Sure once I find what to file it against on kdebugs, plasmashell - general I guess

**Comment by ZaWertun** [comment]
> > Could you create issue, please?
> 
> Sure once I find what to file it against on kdebugs, plasmashell - general I guess

I suggest frameworks-plasma: https://bugs.kde.org/enter_bug.cgi?product=frameworks-plasma&Bugzilla_restrictlogin=on&GoAheadAndLogIn=Log%20in.

**Comment by g6avk** [comment]
Thanks and reported:

https://bugs.kde.org/show_bug.cgi?id=452512

**Comment by g6avk** [comment]
Looks like there is a fix for this now. However your revert in kf5-plasma-5.93.0-2.fc36.x86_64 works fine for me. 
Thanks!

**Comment by g6avk** [comment]
Just updated to 5.94 and it is fixed. I will close this now. 
Thanks again for your COPR 👍🏻
