### ISSUE TITLE
Just FYI kde-connect crash

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#108]
FYI kdeconnect will crash if you open the "settings" in a plugin, like the run commands or notifications plugin. bug report here:

https://bugs.kde.org/show_bug.cgi?id=452903

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/4306497/

**Comment by g6avk** [comment]
I can confirm the new packages fix this. Thanks very much 👍🏻

**Comment by g6avk** [comment]
I'll close this now, no issues at all with the new builds.

**Comment by g6avk** [comment]
A new patch, downloaded and installed and all seems to work fine 👍🏻

**Comment by ZaWertun** [comment]
> A new patch, downloaded and installed and all seems to work fine 👍🏻

Thanks for feedback. We'll wait for upstream fix.
