### ISSUE TITLE
kde-print-manager-libs conflict with official repository

### ISSUE THREAD

**Issue by marco-calautti** [ZaWertun/fedora-copr-kde5#109]
Hi, I am getting the following error when updating with Discover. Updating via dnf did not cause the issue.

Multiple matches of kde-print-manager-libs;22.04.0-1.fc35;x86_64;copr:copr.fedorainfracloud.org:zawertun:kde

**Comment by ZaWertun** [comment]
I think it's because I accidentally created 2 builds with same release (1) in copr.
![изображение](https://user-images.githubusercontent.com/1080298/165480463-c4014cec-19f0-4752-8784-46c685ac2c0b.png)
I'll try to fix it.
