### ISSUE TITLE
Plasma system styles not shown in system settings

### ISSUE THREAD

**Issue by marco-calautti** [ZaWertun/fedora-copr-kde5#111]
With the update to frameworks 5.94, a bug was introduced that makes system settings to not display the default, system-wide styles (i.e., Breeze, Breeze-dark). A recent [merge request](https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/1732) fixed the bug.

Do you think we can see the update in the copr?
It seems the fix has also been cherry picked to plasma 5.24: https://invent.kde.org/plasma/plasma-workspace/-/commit/ae7adb368f52c0b7bf510e3c9cf12e368940745a

Thanks a lot!

**Comment by ZaWertun** [comment]
Build: https://copr.fedorainfracloud.org/coprs/build/4422464.

**Comment by marco-calautti** [comment]
Thanks! As a note, that patch seems to have been applied after this: https://invent.kde.org/plasma/plasma-workspace/-/commit/f77b7284e39b14b0e9a8b4d2b77c0b93b2c9ea59
So I guess, both patches need to be included.

**Comment by ZaWertun** [comment]
Second try: https://copr.fedorainfracloud.org/coprs/build/4422496.

**Comment by marco-calautti** [comment]
Thanks! Hopefully, the order of application of the patches does not matter.

**Comment by ZaWertun** [comment]
It applies cleanly - so obviously order is not important.

```
+ echo 'Patch #0 (plasma-workspace-5.24.5-fix-reading-metadata-in-ThemesModel.patch):'
Patch #0 (plasma-workspace-5.24.5-fix-reading-metadata-in-ThemesModel.patch):
+ /usr/bin/patch --no-backup-if-mismatch -f -p1 -b --suffix .fix-reading-metadata --fuzz=0
patching file kcms/desktoptheme/themesmodel.cpp
+ echo 'Patch #1 (plasma-workspace-5.24.5-find-metadata.json-when-loading-ThemesModel.patch):'
Patch #1 (plasma-workspace-5.24.5-find-metadata.json-when-loading-ThemesModel.patch):
+ /usr/bin/patch --no-backup-if-mismatch -f -p1 -b --suffix .find-metadata.json --fuzz=0
patching file kcms/desktoptheme/themesmodel.cpp
```
