### ISSUE TITLE
[App request] Haruna

### ISSUE THREAD

**Issue by LPW00** [ZaWertun/fedora-copr-kde5#113]
Hi, can you please add the haruna video player to your repo? It's basically just a frontend for mpv, but it's a nice looking one imo. There's a flatpak, but on my arch system the flatpak was significantly slower than the native package, so I assume this to be the case on fedora as well. At least I hope a native one would be faster... 

Here's a link to Haruna https://invent.kde.org/multimedia/haruna

Also, do you have an estimate for when 5.24.90 will be available on Copr?

Thank You!

**Comment by ZaWertun** [comment]
Hello.

> Hi, can you please add the haruna video player to your repo?

Don't think it's possible - both libmpv & ffmpeg dependencies lives in RPMFusion repo.

> Also, do you have an estimate for when 5.24.90 will be available on Copr?

I don't build beta-versions in my copr.

**Comment by LPW00** [comment]
Okay, makes sense. Did you at one point build beta versions and stopped or am I mixing up something? I could almost swear I got beta versions on fedora somehow at some point.

**Comment by ZaWertun** [comment]
> Okay, makes sense. I didn't think about dependencies.
> 
> Did you at one point build beta versions and stopped or am I mixing up something? I could almost swear I got beta versions on fedora somehow at some point.

You can install plasma beta version from marcdeop's copr: https://copr.fedorainfracloud.org/coprs/marcdeop/plasma/.

**Comment by LPW00** [comment]
Thank you! Have a great day!

**Comment by ZaWertun** [comment]
FYI: just added haruna to Fedora repos: https://bodhi.fedoraproject.org/updates/FEDORA-2022-6e750c3ffd.
It's built only for Fedora 37 now, because mpv not built for Fedora 36.
