### ISSUE TITLE
kf5-plasma needs a rebuild with backported patch to fix missing thumbnails in X11

### ISSUE THREAD

**Issue by Fuchs** [ZaWertun/fedora-copr-kde5#115]
Hi ZaWertun, 

thank you very much for your work. Unfortunately a pretty bad build bug managed to sneak into kf5-plasma 5.95, which causes thumbnails to not work in X11. See https://bugs.kde.org/show_bug.cgi?id=455231  for details, there is a fix available in https://invent.kde.org/frameworks/plasma-framework/-/commit/dff1b034c1162062aa2292099d3d01fc53dafdf6  which distro packagers have been made aware of, but maybe not packagers using systems such as copr. 

Could you please create a rebuild of the affected kf5 package(s) with that patch backported?

Thanks in advance, kind regards, 

fox

**Comment by ZaWertun** [comment]
New build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/4538149/

**Comment by Fuchs** [comment]
Thanks, I'll fetch that, test and reply here once it's through :)

**Comment by ZaWertun** [comment]
Just refreshed repo metadata, update should appear after `dnf up --refresh`.
And also don't forget to restart plasmashell after installing it.

**Comment by Fuchs** [comment]
Update works as expected, thanks for the quick fix

**Comment by ZaWertun** [comment]
Thanks for reporting this issue!
