### ISSUE TITLE
krusader not able to open archives (rar, zip) any more

### ISSUE THREAD

**Issue by slartibart70** [ZaWertun/fedora-copr-kde5#116]
Hi,
after the latest updates on fedora35 (plasma 5.24.5) and fedora36 (plasma 5.25) krusader is not able to open and show (inline in the panel) the contents of zip or rar archives any more.
Works ok on 5.24.5, but i think the kio-slave updates (kf5 frameworks??) must be responsible for this, before this update it worked fine.

Interestingly, dolphin can display zip archives, but not 7z archives.
krusader can still display tgz or tar archives 

Anything you can do to help here?

**Comment by slartibart70** [comment]
maybe it's just the krarc component in krusader
you see (when opening an archive) in the location bar only this
`krarc: > home > > > > >`
The bottom only shows 'Reading...'

whereas a tar archive shows something like this
`tar: > home > user > data.tgz

**Comment by slartibart70** [comment]
i downgraded kf5-kio-\* from 5.95.0 to 5.94.0
and...all is fine (again)

still annoying not being able to use the new kio version, though

**Comment by ZaWertun** [comment]
You should definitly report this bug at https://bugs.kde.org/.

**Comment by ZaWertun** [comment]
Just checked Krusader in KDE Neon with same kf5-kio version - same issue spotted.

**Comment by slartibart70** [comment]
> You should definitly report this bug at https://bugs.kde.org/.

already done: https://bugs.kde.org/show_bug.cgi?id=455447

**Comment by ZaWertun** [comment]
Actually I've managed to fix this bug with this patch:
```
diff --git a/krusader/FileSystem/filesystem.cpp b/krusader/FileSystem/filesystem.cpp
index c05c47f5..9ff867e8 100644
--- a/krusader/FileSystem/filesystem.cpp
+++ b/krusader/FileSystem/filesystem.cpp
@@ -94,10 +94,10 @@ bool FileSystem::scanOrRefresh(const QUrl &directory, bool onlyScan)
 
     // workaround for krarc: find out if transition to local fs is wanted and adjust URL manually
     QUrl url = directory;
-    if (_currentDirectory.scheme() == "krarc" && url.scheme() == "krarc" &&
-        QDir(url.path()).exists()) {
-        url.setScheme("file");
-    }
+//     if (_currentDirectory.scheme() == "krarc" && url.scheme() == "krarc" &&
+//         QDir(url.path()).exists()) {
+//         url.setScheme("file");
+//     }
 
     const bool dirChange = !url.isEmpty() && cleanUrl(url) != _currentDirectory;
 
```

I don't know if it's valid fix or not though...

**Comment by ZaWertun** [comment]
```patch
diff --git a/krusader/FileSystem/filesystem.cpp b/krusader/FileSystem/filesystem.cpp
index c05c47f5..17147cfd 100644
--- a/krusader/FileSystem/filesystem.cpp
+++ b/krusader/FileSystem/filesystem.cpp
@@ -94,10 +94,12 @@ bool FileSystem::scanOrRefresh(const QUrl &directory, bool onlyScan)
 
     // workaround for krarc: find out if transition to local fs is wanted and adjust URL manually
     QUrl url = directory;
+#if KIO_VERSION < QT_VERSION_CHECK(5, 95, 0)
     if (_currentDirectory.scheme() == "krarc" && url.scheme() == "krarc" &&
         QDir(url.path()).exists()) {
         url.setScheme("file");
     }
+#endif
 
     const bool dirChange = !url.isEmpty() && cleanUrl(url) != _currentDirectory;
 
```

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/build/4544873

**Comment by ZaWertun** [comment]
Just double checked - patch is not helping at all 🤦‍♂️
Actually it's working when I'm using version built locally, not from the package.
Maybe something wrong with LTO or some compiler flag affects it...

**Comment by ZaWertun** [comment]
Actually this bug was fixed in master, I'll build latest commit in my copr - issue should gone.

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/build/4544920

**Comment by ZaWertun** [comment]
One more build with translations from latest stable version: https://copr.fedorainfracloud.org/coprs/build/4544989.

**Comment by slartibart70** [comment]
thanks for merging,
no more problems with current release in krusader
