### ISSUE TITLE
[Feature Request] KDE-EDU applications

### ISSUE THREAD

**Issue by bugzy** [ZaWertun/fedora-copr-kde5#12]
Is there any chance you can add kde education applications[1] to the builds. Specifically, I am thinking about ktouch, kbibtex, and marble.

[1] https://kde.org/applications/education/

**Comment by ZaWertun** [comment]
FYI: Marble already has been built as dep for digikam.

**Comment by bugzy** [comment]
Great. Thanks

**Comment by ZaWertun** [comment]
FYI: just added some educational KDE applications.
There is a list:
```
analitza
artikulate
blinken
cantor
kalzium
kanagram
kbruch
kdeedu-data
kgeography
khangman
kig
kigo
kiten
klettres
kmplot
ktouch
kturtle
kwordquiz
libkeduvocdocument
minuet
parley
rocs
step
```

**Comment by bugzy** [comment]
Greatly appreciated. Thanks

**Comment by ZaWertun** [comment]
If something still missing - let me know.

**Comment by bugzy** [comment]
I think that is it. Thanks for working on this.
