### ISSUE TITLE
Unable to remove manually added wallpaper

### ISSUE THREAD

**Issue by popov895** [ZaWertun/fedora-copr-kde5#121]
SUMMARY

It's not possible to remove manually added wallpapers, because the button to delete it isn't visible. There is no such issue in openSUSE Tumbleweed and KDE neon.

STEPS TO REPRODUCE

1. Open wallpaper settings (right click on desktop > "Configure Desktop and Wallpaper")
2. Add custom wallpaper
3. Close window
4. Open that window again

OBSERVED RESULT

The button to delete custom added wallpaper isn't visible

EXPECTED RESULT

The button to delete custom added wallpaper is visible

SOFTWARE/OS VERSIONS

Operating System: Fedora Linux 36
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.3
Graphics Platform: X11

**Comment by ZaWertun** [comment]
As temporary workaround wallpaper can be removed after selecting it as active. Delete button appears afterwards.

**Comment by ZaWertun** [comment]
I'm able to reproduce this bug with latest KDE Neon (neon-user-20220721-0952), I'll make video.

**Comment by ZaWertun** [comment]
https://user-images.githubusercontent.com/1080298/180455275-407b33f4-bdea-4f62-9660-aa6d1601d9a3.mp4

**Comment by ZaWertun** [comment]
Issue: https://bugs.kde.org/show_bug.cgi?id=457019
(Can't remove manually added wallpaper)

**Comment by popov895** [comment]
Indeed, it can be reproduced on the KDE Neon. Sorry I didn't check it well. I think this bug report can be closed here as an upstream.

**Comment by ZaWertun** [comment]
> Indeed, it can be reproduced on the KDE Neon. Sorry I didn't check it well. I think this bug report can be closed here as an upstream.

No problem :)

**Comment by ZaWertun** [comment]
Build with patch: https://copr.fedorainfracloud.org/coprs/build/4683230.

**Comment by ZaWertun** [comment]
PR for Fedora 36 package: https://src.fedoraproject.org/rpms/plasma-workspace/pull-request/18.

**Comment by popov895** [comment]
Great, thanks!

**Comment by ZaWertun** [comment]
> Great, thanks!

Merged my other PR for rawhide: https://src.fedoraproject.org/rpms/plasma-workspace/pull-request/19.
Let's wait when package would be built for Fedora 36.
