### ISSUE TITLE
Vertical progress bars in KTorrent

### ISSUE THREAD

**Issue by marco-calautti** [ZaWertun/fedora-copr-kde5#122]
Recently, KTorrent progress bars started appearing vertically rather than horizontally, causing a very narrow progress bar to appear. It seems this has to do with the default behaviour of progress bars in Breeze and Oxygen. This merge request seems to fix the issue (which is also very well described with pictures): https://invent.kde.org/network/ktorrent/-/merge_requests/62

Would you consider including it in your repo?

**Comment by ZaWertun** [comment]
Build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/4687817/.

**Comment by ZaWertun** [comment]
Fedora package PR: https://src.fedoraproject.org/rpms/ktorrent/pull-request/1

Thanks!

**Comment by marco-calautti** [comment]
Thanks. It seems the update has caused some packages with conflicts:
kdeconnectd                          x86_64             22.04.1-3.fc36              updates                                                  27 k
 kdeconnectd                          x86_64             22.04.2-1.fc36              copr:copr.fedorainfracloud.org:zawertun:kde              28 k
 qt5-qtbase                           x86_64             5.15.3-1.fc36               fedora                                                  3.6 M
 qt5-qtbase                           x86_64             5.15.5-2.fc36               updates                                                 3.5 M
 qt5-qtbase-gui                       x86_64             5.15.3-1.fc36               fedora                                                  6.3 M
 qt5-qtbase-gui                       x86_64             5.15.5-2.fc36               updates                                                 6.3 M

**Comment by ZaWertun** [comment]
> Thanks. It seems the update has caused some packages with conflicts: kdeconnectd x86_64 22.04.1-3.fc36 updates 27 k kdeconnectd x86_64 22.04.2-1.fc36 copr:copr.fedorainfracloud.org:zawertun:kde 28 k qt5-qtbase x86_64 5.15.3-1.fc36 fedora 3.6 M qt5-qtbase x86_64 5.15.5-2.fc36 updates 3.5 M qt5-qtbase-gui x86_64 5.15.3-1.fc36 fedora 6.3 M qt5-qtbase-gui x86_64 5.15.5-2.fc36 updates 6.3 M

It's caused by Qt update, all packages dependent on Qt private libraries should be rebuilt.

**Comment by ZaWertun** [comment]
Should be resolved now - try to update again (with `--refresh` flag).
