### ISSUE TITLE
Fedora updates wants to replace kwin and others

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#123]
Fedora updates wants to replace your builds - kwin, plasma-workspace, sddm-breeze, kf5-kdeclarative, kuserfeedback, kf5-kguiaddons

I am guessing due to the Qt update?

**Comment by ZaWertun** [comment]
Thanks, I'll update those packages too.

**Comment by g6avk** [comment]
Think I found a couple more:
kf5-kwayland, kwayland-integration

**Comment by g6avk** [comment]
Thanks, all updated OK now with your packages 👍🏻
