### ISSUE TITLE
coretemp sensor isn't available in the System Monitor

### ISSUE THREAD

**Issue by popov895** [ZaWertun/fedora-copr-kde5#125]
SUMMARY

The coretemp sensor (from lm_sensors) isn't available in the System Monitor, although all other sensors are available. At the same time, this sensor is available in KSysGuard. This seems to be a maintenance issue, since the coretemp is available in both KSysGuard and System Monitor on openSUSE Tumbleweed.

See [BUG 438963](https://bugs.kde.org/show_bug.cgi?id=438963)

![ksysguard](https://user-images.githubusercontent.com/24252473/182102130-c3587741-8478-40e6-b97e-024d5289c44d.png)
![system_monitor](https://user-images.githubusercontent.com/24252473/182102149-dd25a04a-c0f6-4a3f-a7ec-99fe405fb13b.png)

SOFTWARE/OS VERSIONS

Operating System: Fedora Linux 36
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.13-200.fc36.x86_64 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by ZaWertun** [comment]
Thanks for the report, I'll check this on my PCs.

**Comment by ZaWertun** [comment]
Do you have AMD or Intel CPU? Just in case.

**Comment by ZaWertun** [comment]
Actually there is a blacklist for some sensors: https://invent.kde.org/plasma/ksystemstats/-/blob/15a03830/plugins/lmsensors/lmsensors.cpp#L24.
And `coretemp` is one of the blacklisted items...

See this bug: https://bugs.kde.org/show_bug.cgi?id=438318#c37.

**Comment by popov895** [comment]
Ah, I see, thanks. Sorry to have bothered you.

**Comment by ZaWertun** [comment]
> Ah, I see, thanks. Sorry to have bothered you.

No problem :)
