### ISSUE TITLE
Display settings crashes on Wayland

### ISSUE THREAD

**Issue by rnovacek** [ZaWertun/fedora-copr-kde5#127]
With latest updates from `zawertun/kde` COPR, I'm getting crashes when opening systemsettings -> Display and Monitor.

When running systemsettings from console, this is the output:
```
QQmlEngine::setContextForObject(): Object already has a QQmlContext
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
kf.coreaddons: "Could not load plugin from kcm_kscreen: The shared library was not found."
QQmlEngine::setContextForObject(): Object already has a QQmlContext
The Wayland connection broke. Did the Wayland compositor die?
The Wayland connection broke. Did the Wayland compositor die?
```

`kscreen-doctor -o` crashes with the same error: `The Wayland connection broke. Did the Wayland compositor die?`

Output of `kscreen-doctor -i`:

```
Environment: 
  * KSCREEN_BACKEND           : [not set]
  * KSCREEN_BACKEND_INPROCESS : [not set]
  * KSCREEN_LOGGING           : [not set]
Logging to                : [logging disabled]
Preferred KScreen backend : KSC_KWayland.so
Available KScreen backends:
  * KSC_Fake.so: /usr/lib64/qt5/plugins/kf5/kscreen/KSC_Fake.so
  * KSC_KWayland.so: /usr/lib64/qt5/plugins/kf5/kscreen/KSC_KWayland.so
  * KSC_QScreen.so: /usr/lib64/qt5/plugins/kf5/kscreen/KSC_QScreen.so
  * KSC_XRandR.so: /usr/lib64/qt5/plugins/kf5/kscreen/KSC_XRandR.so
  * KSC_XRandR11.so: /usr/lib64/qt5/plugins/kf5/kscreen/KSC_XRandR11.so
```

It was running fine before some recent updates.

kscreen-5.25.4-1.fc36.x86_64
libkscreen-qt5-5.25.4-1.fc36.x86_64
kf5-plasma-5.96.0-1.fc36.x86_64
plasma-desktop-5.25.4-1.fc36.x86_64
kwin-wayland-5.25.4-1.fc36.x86_64

**Comment by rnovacek** [comment]
Works fine after restart, but it has happened before. Maybe something crashes (on suspend?). I'll try to get more information. Any ideas where to look for some logs?

**Comment by ZaWertun** [comment]
> Works fine after restart, but it has happened before. Maybe something crashes (on suspend?). I'll try to get more information. Any ideas where to look for some logs?

Do you have nvidia video card?
It can be caused by the driver update.

**Comment by rnovacek** [comment]
I have AMD Ryzen 4700U with integrated AMD graphic card. I'll keep monitoring it and if it doesn't happen again in few days, I'll close this issue.

**Comment by rnovacek** [comment]
Seems to be working fine now, so I assume it was just a fluke. I'll close it now and reopen if it happens again.
