### ISSUE TITLE
Breeze icons are missing icons of some sizes

### ISSUE THREAD

**Issue by popov895** [ZaWertun/fedora-copr-kde5#128]
Breeze icons are missing icons of some sizes (e.g. `24`, `24@2` and `24@3` for actions). This causes some GTK applications to use icons of the wrong size:

![gcyz3hhs0bh91](https://user-images.githubusercontent.com/24252473/184604085-43d3d2ba-dfa3-49e6-9d2c-4fa57c8a542b.png)

Icons of these sizes should be generated automatically, but judging by their absence, this doesn't happen.

See:
- https://invent.kde.org/frameworks/breeze-icons/-/commit/d0582a4f16bdf3947a085c31c5a0136e6283e7a1
- https://invent.kde.org/frameworks/breeze-icons/-/blob/v5.97.0/generate-24px-versions.py

**Comment by ZaWertun** [comment]
Thanks for feedback!

According to output from builder-live.log package `python3-lxml` is missing:
```
running /usr/bin/python3.10 -c "import lxml; from lxml import etree; print(lxml.get_include())"  2>&1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lxml'
CMake Warning at CMakeLists.txt:42 (message):
  lxml or lxml.etree not found; icon generation disabled
```

**Comment by ZaWertun** [comment]
Build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/4732299/

**Comment by popov895** [comment]
Awesome, thanks!
