### ISSUE TITLE
[Feature Request] Zanshin

### ISSUE THREAD

**Issue by bugzy** [ZaWertun/fedora-copr-kde5#13]
Any chance Zanshin[1] can be added to the build list. See an older spec file [2]

[1] https://github.com/KDE/zanshin/releases
[2] https://src.fedoraproject.org/rpms/zanshin/blob/master/f/zanshin.spec

**Comment by ZaWertun** [comment]
But `zanshin` is available in the Fedora repos (version 0.5.0).
It's not working with kf5 libs built from my repo or what?

**Comment by bugzy** [comment]
The actual issue is that zanshin 0.5.0 in the fedora repos and elsewhere is broken as described here [1, 2]. I believe that a release [3] was made to fix the problem, but the fedora repos have not yet picked it up, even in rawhide. 

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1761313
[2] https://bugs.kde.org/show_bug.cgi?id=411339
[3] https://github.com/KDE/zanshin/releases/tag/0.5.71

**Comment by ZaWertun** [comment]
Try this build - https://copr.fedorainfracloud.org/coprs/zawertun/kde-extra/build/1117051/

**Comment by bugzy** [comment]
@ZaWertun the build works! A few points to note:
1. If a user has renku installed, there will be package conflicts because renku depends on zanshin-common. 
2. This is probably not package related, but the full UI is not displayed when Zanshin is run as a standalone application. However, the entire UI is just fine when inside Kontact. 
Thanks for doing this!

**Comment by ZaWertun** [comment]
2. When I run renku from the console as standalone it starts long enough, some DB update takes place.

**Comment by ZaWertun** [comment]
1. Renku was removed from Zenshin codebase (as of version 0.5.71).
I'll add conflicts with renku <= 0.5.0

**Comment by bugzy** [comment]
I see. Great. Thanks again.
