### ISSUE TITLE
Can't set shortcut to launch Kate

### ISSUE THREAD

**Issue by popov895** [ZaWertun/fedora-copr-kde5#133]
If I set shortcut to launch Kate and then activate it, nothing happens. Shortcuts for other apps works well.

![Screenshot_20220821_145232](https://user-images.githubusercontent.com/24252473/185789621-7582a8d0-cd36-4a45-824d-a0ea996b4906.png)

Looks like launching apps with arguments via shortcuts in broken.

**Comment by popov895** [comment]
Seems that this MR fixes this issue: https://invent.kde.org/frameworks/kglobalaccel/-/commit/625b53f516d27eb61eaad00175dd7108bf82572f

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/build/4752607

**Comment by ZaWertun** [comment]
You could try `kf5-kglobalaccel-5.97.0-2.fc36`.

**Comment by popov895** [comment]
Now it works, thanks!
