### ISSUE TITLE
Obscure text in kmail's message list settings

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#136]
Hi,

Can any kmail/kontact user confirm the odd text in:

Settings > configure > appearance > message list, see screen shot.

First seen in F36 and F37 (thanks for the F37 repo 👍🏻 )

![Screenshot_20220917_212229](https://user-images.githubusercontent.com/4700941/191002909-bf6b5f2c-56b7-48a6-9858-4bf7e3cc5fcd.jpeg)

**Comment by ZaWertun** [comment]
Same text displayed for me, I'll rebuild kmail package maybe it will help...

**Comment by ZaWertun** [comment]
Rebuild doesn't help at all, I'll check KDE Neon for same bug.

**Comment by g6avk** [comment]
Thanks for testing,
Laurent Montel remarked it is a i18n problem not kmail.

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/4864007/

**Comment by ZaWertun** [comment]
Should be fixed in kmail-22.08.1-2.

**Comment by g6avk** [comment]
Confirmed fixed, thank you!

![Screenshot_20220919_233220](https://user-images.githubusercontent.com/4700941/191131153-656b8ad4-82be-4e42-a6d7-acfb58a6a0bd.jpeg)
