### ISSUE TITLE
kf5-kirigami2 rebuild?

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#138]
With the new qt5 updates there seems to be an issue (I think) with kf5-kirigami2

Problem: package kf5-kirigami2-5.98.0-1.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.5, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.6-1.fc37.x86_64 and qt5-qtbase-5.15.5-4.fc37.x86_64
  - cannot install the best update candidate for package qt5-qtbase-5.15.5-4.fc37.x86_64
  - cannot install the best update candidate for package kf5-kirigami2-5.98.0-1.fc37.x86_64

**Comment by ZaWertun** [comment]
Hello.
It should be fixed in recent builds for Fedora 37:
![изображение](https://user-images.githubusercontent.com/1080298/192099642-1a8f7936-4628-4d09-a9ef-ecf4c00ef4a7.png)

I've tested it on test VM - looks good.
Run `sudo dnf up --refresh` to update.

**Comment by g6avk** [comment]
I did try refresh before I posted here :-)
So I tried dnfdragora and it worked for some reason. It replaced kirigami2 during the update but not your package/repo?

rpm -qi kf5-kirigami2

Name        : kf5-kirigami2
Version     : 5.98.0
Release     : 1.fc37
Architecture: x86_64
Install Date: Sat 24 Sep 2022 14:18:50 BST
Group       : Unspecified
Size        : 1815370
License     : GPLv2+
Signature   : RSA/SHA256, Fri 16 Sep 2022 17:25:03 BST, Key ID f55ad3fb5323552a
Source RPM  : kf5-kirigami2-5.98.0-1.fc37.src.rpm
Build Date  : Fri 16 Sep 2022 11:43:10 BST
Build Host  : buildvm-x86-08.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project

**Comment by ZaWertun** [comment]
Ok, I'll rebuild kf5-kirigami2 too. One sec.

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/build/4871440

**Comment by ZaWertun** [comment]
Done.

**Comment by g6avk** [comment]
That was quick!! 

Vendor      : Fedora Copr - user zawertun

Thanks very much 👍🏻
