### ISSUE TITLE
[Missing Package] Plasma Thunderbolt

### ISSUE THREAD

**Issue by bugzy** [ZaWertun/fedora-copr-kde5#14]
With the release of Plasma 5.17, plasma-thunderbolt is now available [1]

[1] https://copr.fedorainfracloud.org/coprs/ptoscano/plasma-thunderbolt/

**Comment by ZaWertun** [comment]
Thanks for the information :)

I'll add this package as soon as possible, I'm just in the middle of plasma update process (5.17).

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1058555/

**Comment by bugzy** [comment]
Excellent. Thanks
