### ISSUE TITLE
baloo default config

### ISSUE THREAD

**Issue by popov895** [ZaWertun/fedora-copr-kde5#144]
I found that `baloo` by default (if `~/.config/baloofilerc` is missing) doesn't index the entire home folder, but only some folders inside it: Documents, Music, Pictures and Videos. This behavior differs from the default behavior (tested in KDE neon and openSUSE Tumbleweed).

In order to index the entire home folder, I have to add/remove each new folder inside it manually, which isn't very convenient. To avoid doing this, I can add the entire home folder to the list for indexing, but then my baloo settings look like this (it''s not clear whether it's indexed or not):

![Screenshot_20221009_182501](https://user-images.githubusercontent.com/24252473/194766253-31fc6a05-3af1-449f-9e51-0d31fce5530e.png)

and I also get the following error:

```
kf.baloo: Failed to add exclude folder config entry for "/home/epopov/"
```
I found that there's global `baloofilerc` (`/usr/share/kde-settings/kde-profile/default/xdg/baloofilerc`):

```
[General]
exclude folders[$e]=$HOME
```
But deleting this file also doesn't solve this issue. Then looking at the sources of your repository, I found a [patch](https://github.com/ZaWertun/fedora-copr-kde5/blob/master/KF5/kf5-baloo/baloo-5.67.0-baloofile_config.patch) that also excludes the home folder from the list for indexing.

So, is there any reason why the home folder is removed from the list for indexing by default? And if not, is it possible to remove this patch?

**Comment by ZaWertun** [comment]
This patch was added to avoid indexing of all $HOME dir content.
It can cause very high CPU & disk load, because by default Baloo will index not only file names but also contents of the files.

I think it could be replaced with config with content indexing disabled by default (`onlyBasicIndexing := true`).

**Comment by popov895** [comment]
Great, this is the default configuration of the `baloo` on openSUSE Tumbleweed.

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/build/4898021

**Comment by popov895** [comment]
Thanks!
