### ISSUE TITLE
[Request] Refresh 5.26.0 with wayland display fix

### ISSUE THREAD

**Issue by r2rX** [ZaWertun/fedora-copr-kde5#146]
Hey @ZaWertun 

There was a small regression/issue with 5.26, regarding a [multi-monitor config issue](https://bugs.kde.org/show_bug.cgi?id=460247). Fortunately, there is a fix for it with this [merge request](https://invent.kde.org/plasma/kwin/-/merge_requests/3050) that went through.

Any chance to recompile 5.26 with this fix? :) Cheers!

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/4919393/

**Comment by r2rX** [comment]
Nice, dude! Thanks a mill. ;)

**Comment by ZaWertun** [comment]
Done

**Comment by r2rX** [comment]
Happy to report that it's working. Thanks again, @ZaWertun !
