### ISSUE TITLE
Fedora kf5-kimageformats update

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#149]
Fedora wants to update kf5-kimageformats to version 5.99.0-2.fc37, apparently there are some upstream patches.

**Comment by ZaWertun** [comment]
There is patches to fix very high CPU usage when using animated wallpapers.
I'll merge it.

**Comment by ZaWertun** [comment]
Still can't build - copr is not available right now: https://docs.google.com/spreadsheets/d/1URopuw2R533H6i4vSTH8Nt47EIhs3ubWcLUXvRcxTRQ/edit#gid=0

**Comment by g6avk** [comment]
OK no problem

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/4986452/

**Comment by g6avk** [comment]
Thanks! however that link was broken but I found the package :)

New issue, I think it needs to be built with the new libavif which is in updates-testing as when updating I get this:

Problem 1: package kf5-kimageformats-5.99.0-5.fc37.x86_64 requires libavif.so.14()(64bit)

**Comment by ZaWertun** [comment]
This update: https://bodhi.fedoraproject.org/updates/FEDORA-2022-5b019245ff
Let's wait when it's got to stable.

**Comment by g6avk** [comment]
OK no problem 👍🏻

**Comment by g6avk** [comment]
I think we can close now this as the offending update packages have been unpushed.
