### ISSUE TITLE
kcm_systemd conflict

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#15]
Problem: package plasma-systemsettings-5.17.0-2.fc30.x86_64 conflicts with kcm_systemd provided by kcm_systemd-1.2.1-15.fc30.x86_64

I can get around this by removing kcm_systemd.

**Comment by ZaWertun** [comment]
Yep, I add `Conflicts` to spec because one file exists in both packages (see plasma-settings.spec).

I can rename conflicting file in the plasma-settings, most likely it will not break anything.

Then I will remove conflict with kcm_systemd.

**Comment by ZaWertun** [comment]
Please test this build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1063008/.
If all is OK I'll regenerate repo metadata.

**Comment by g6avk** [comment]
OK, I updated plasma-settings and now kcm_systemd installs no problem and 
kcm_systemd seem's to be working fine.
