### ISSUE TITLE
dnf update plasma-desktop [protected packages]

### ISSUE THREAD

**Issue by architectlin** [ZaWertun/fedora-copr-kde5#151]
update does not work 

The operation would result in removing the following protected packages: plasma-desktop

**Comment by ZaWertun** [comment]
Yeah, I know. It's because of Qt update. I'll do rebuild today.

**Comment by ZaWertun** [comment]
Try to update again, it should be fixed now.

**Comment by architectlin** [comment]
same problem

dnf clean all
sudo dnf upgrade --refresh --best --allowerasing

**Comment by ZaWertun** [comment]
Could you post full logs?
I've just updated Fedora 37 on 2 of my VMs - all is ok.
Also `dnf clean all` should be runned with `sudo` too.

**Comment by g6avk** [comment]
What are you updating, I had no issues updating this FC37 box (not a VM)

Operating System: Fedora Linux 37
KDE Apps  22.08.3
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.7
Kernel Version: 6.0.9-300.fc37.x86_64 (64-bit)

Also "clean all" is not really needed, use "sudo dnf clean metadata" that way you keep the downloaded packages assuming you have that set in dnf.conf Clean all removes everything.

**Comment by architectlin** [comment]
`[root@yuntani-desk stefan]# dnf upgrade 
Last metadata expiration check: 0:00:25 ago on Thu 17 Nov 2022 08:28:38 PM CET.
Dependencies resolved.

 Problem 1: package qt5-qtwebengine-freeworld-5.15.10-2.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.6, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.7-1.fc37.x86_64 and qt5-qtbase-5.15.6-1.fc37.x86_64
  - cannot install the best update candidate for package qt5-qtwebengine-freeworld-5.15.10-2.fc37.x86_64
  - cannot install the best update candidate for package qt5-qtbase-5.15.6-1.fc37.x86_64
 Problem 2: package obs-studio-libs-28.1.2-1.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.6, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.7-1.fc37.x86_64 and qt5-qtbase-5.15.6-1.fc37.x86_64
  - package python3-qt5-base-5.15.6-9.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.7, but none of the providers can be installed
  - cannot install the best update candidate for package python3-qt5-base-5.15.6-8.fc37.x86_64
  - cannot install the best update candidate for package obs-studio-libs-28.1.2-1.fc37.x86_64
 Problem 3: problem with installed package qt5-qtwebengine-freeworld-5.15.10-2.fc37.x86_64
  - package qt5-qtwebengine-freeworld-5.15.10-2.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.6, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.7-1.fc37.x86_64 and qt5-qtbase-5.15.6-1.fc37.x86_64
  - package qt5-qdbusviewer-5.15.7-1.fc37.x86_64 requires qt5-qtbase(x86-64) >= 5.15.7, but none of the providers can be installed
  - cannot install the best update candidate for package qt5-qdbusviewer-5.15.6-1.fc37.x86_64
 Problem 4: package obs-studio-28.1.2-1.fc37.x86_64 requires libobs-frontend-api.so.0()(64bit), but none of the providers can be installed
  - package obs-studio-28.1.2-1.fc37.x86_64 requires libobs.so.0()(64bit), but none of the providers can be installed
  - package obs-studio-28.1.2-1.fc37.x86_64 requires obs-studio-libs(x86-64) = 28.1.2-1.fc37, but none of the providers can be installed
  - package obs-studio-libs-28.1.2-1.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.6, but none of the providers can be installed
  - package qt5-qtbase-5.15.6-1.fc37.x86_64 requires qt5-qtbase-common = 5.15.6-1.fc37, but none of the providers can be installed
  - cannot install both qt5-qtbase-common-5.15.7-1.fc37.noarch and qt5-qtbase-common-5.15.6-1.fc37.noarch
  - cannot install the best update candidate for package qt5-qtbase-common-5.15.6-1.fc37.noarch
  - cannot install the best update candidate for package obs-studio-28.1.2-1.fc37.x86_64
 Problem 5: problem with installed package obs-studio-libs-28.1.2-1.fc37.x86_64
  - package obs-studio-libs-28.1.2-1.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.6, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.7-1.fc37.x86_64 and qt5-qtbase-5.15.6-1.fc37.x86_64
  - package qt5-qtbase-gui-5.15.7-1.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.7-1.fc37, but none of the providers can be installed
  - cannot install the best update candidate for package qt5-qtbase-gui-5.15.6-1.fc37.x86_64
 Problem 6: problem with installed package obs-studio-28.1.2-1.fc37.x86_64
  - package obs-studio-28.1.2-1.fc37.x86_64 requires libobs-frontend-api.so.0()(64bit), but none of the providers can be installed
  - package obs-studio-28.1.2-1.fc37.x86_64 requires libobs.so.0()(64bit), but none of the providers can be installed
  - package obs-studio-28.1.2-1.fc37.x86_64 requires obs-studio-libs(x86-64) = 28.1.2-1.fc37, but none of the providers can be installed
  - package obs-studio-libs-28.1.2-1.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.6, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.7-1.fc37.x86_64 and qt5-qtbase-5.15.6-1.fc37.x86_64
  - package qt5-qtbase-mysql-5.15.7-1.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.7-1.fc37, but none of the providers can be installed
  - cannot install the best update candidate for package qt5-qtbase-mysql-5.15.6-1.fc37.x86_64
==========================================================================================================================================================================================
 Package                                                        Architecture                       Version                                      Repository                           Size
==========================================================================================================================================================================================
Upgrading:
 expat                                                          i686                               2.5.0-1.fc37                                 updates                             115 k
 expat                                                          x86_64                             2.5.0-1.fc37                                 updates                             110 k
 gpredict                                                       x86_64                             2.2.1-13.fc37                                updates                             3.9 M
 hamlib                                                         x86_64                             4.5-1.fc37                                   updates                             1.3 M
 ibus-typing-booster                                            noarch                             2.19.8-1.fc37                                updates                             1.1 M
 pipewire                                                       i686                               0.3.60-4.fc37                                updates                              46 k
 pipewire                                                       x86_64                             0.3.60-4.fc37                                updates                              46 k
 pipewire-alsa                                                  i686                               0.3.60-4.fc37                                updates                              63 k
 pipewire-alsa                                                  x86_64                             0.3.60-4.fc37                                updates                              64 k
 pipewire-gstreamer                                             x86_64                             0.3.60-4.fc37                                updates                              58 k
 pipewire-jack-audio-connection-kit                             x86_64                             0.3.60-4.fc37                                updates                             136 k
 pipewire-libs                                                  i686                               0.3.60-4.fc37                                updates                             1.7 M
 pipewire-libs                                                  x86_64                             0.3.60-4.fc37                                updates                             1.7 M
 pipewire-pulseaudio                                            x86_64                             0.3.60-4.fc37                                updates                              28 k
 pipewire-utils                                                 x86_64                             0.3.60-4.fc37                                updates                             342 k
 pugixml                                                        x86_64                             1.13-1.fc37                                  updates                             100 k
 qt5-qtcharts                                                   x86_64                             5.15.7-1.fc37                                updates                             684 k
 qt5-qtdatavis3d                                                x86_64                             5.15.7-1.fc37                                updates                             556 k
 qt5-qttranslations                                             noarch                             5.15.7-1.fc37                                updates                             2.0 M
 qt5-srpm-macros                                                noarch                             5.15.7-1.fc37                                updates                             7.9 k
 speech-dispatcher                                              x86_64                             0.11.4-1.fc37                                updates                             4.4 M
 speech-dispatcher-espeak-ng                                    x86_64                             0.11.4-1.fc37                                updates                              36 k
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 qt5-qtbase                                                     x86_64                             5.15.7-1.fc37                                updates                             3.6 M
 qt5-qtbase-common                                              noarch                             5.15.7-1.fc37                                updates                              12 k
Skipping packages with broken dependencies:
 python3-qt5-base                                               x86_64                             5.15.6-9.fc37                                updates                             3.3 M
 qt5-qdbusviewer                                                x86_64                             5.15.7-1.fc37                                updates                              56 k
 qt5-qtbase-gui                                                 x86_64                             5.15.7-1.fc37                                updates                             6.4 M
 qt5-qtbase-mysql                                               x86_64                             5.15.7-1.fc37                                updates                              42 k

Transaction Summary
==========================================================================================================================================================================================
Upgrade  22 Packages
Skip      6 Packages

Total download size: 18 M
Is this ok [y/N]:     
`

`[root@yuntani-desk stefan]# dnf upgrade --best --allowerasing
AnyDesk Fedora - stable                                                                                                                                   3.5 kB/s | 1.6 kB     00:00    
Copr repo for kde owned by zawertun                                                                                                                       5.2 MB/s | 4.0 MB     00:00    
Docker CE Stable - x86_64                                                                                                                                  38 kB/s | 8.7 kB     00:00    
Fedora 37 - x86_64                                                                                                                                         15 MB/s |  64 MB     00:04    
Fedora 37 openh264 (From Cisco) - x86_64                                                                                                                  5.7 kB/s | 2.5 kB     00:00    
Fedora Modular 37 - x86_64                                                                                                                                4.6 MB/s | 3.0 MB     00:00    
Fedora 37 - x86_64 - Updates                                                                                                                              8.7 MB/s |  14 MB     00:01    
Fedora Modular 37 - x86_64 - Updates                                                                                                                      5.1 MB/s | 3.7 MB     00:00    
google-chrome                                                                                                                                              17 kB/s | 3.6 kB     00:00    
RPM Fusion for Fedora 37 - Free                                                                                                                           1.2 MB/s | 683 kB     00:00    
RPM Fusion for Fedora 37 - Free tainted                                                                                                                   3.9 kB/s | 1.8 kB     00:00    
RPM Fusion for Fedora 37 - Free - Updates                                                                                                                  17 kB/s | 8.3 kB     00:00    
RPM Fusion for Fedora 37 - Nonfree                                                                                                                        467 kB/s | 248 kB     00:00    
RPM Fusion for Fedora 37 - Nonfree - Steam                                                                                                                4.8 kB/s | 2.2 kB     00:00    
RPM Fusion for Fedora 37 - Nonfree tainted                                                                                                                8.0 kB/s | 3.8 kB     00:00    
RPM Fusion for Fedora 37 - Nonfree - Updates                                                                                                              2.5 kB/s | 1.2 kB     00:00    
Visual Studio Code                                                                                                                                         13 MB/s |  30 MB     00:02    
Error: 
 Problem: The operation would result in removing the following protected packages: plasma-desktop
(try to add '--skip-broken' to skip uninstallable packages)
`

**Comment by architectlin** [comment]
root@yuntani-desk stefan]# dnf upgrade --best --allowerasing
Last metadata expiration check: 0:03:52 ago on Thu 17 Nov 2022 08:28:38 PM CET.
Error: 
 Problem: The operation would result in removing the following protected packages: plasma-desktop
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by architectlin** [comment]
`[root@yuntani-desk stefan]# dnf remove qt5-qtwebengine-freeworld
Dependencies resolved.
==========================================================================================================================================================================================
 Package                                               Architecture                       Version                                       Repository                                   Size
==========================================================================================================================================================================================
Removing:
 qt5-qtwebengine-freeworld                             x86_64                             5.15.10-2.fc37                                @rpmfusion-free                             131 M

Transaction Summary
==========================================================================================================================================================================================
Remove  1 Package

Freed space: 131 M
Is this ok [y/N]: j
Is this ok [y/N]: j
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                  1/1 
  Erasing          : qt5-qtwebengine-freeworld-5.15.10-2.fc37.x86_64                                                                                                                  1/1 
  Verifying        : qt5-qtwebengine-freeworld-5.15.10-2.fc37.x86_64                                                                                                                  1/1 

Removed:
  qt5-qtwebengine-freeworld-5.15.10-2.fc37.x86_64                                                                                                                                         

Complete!
`

**Comment by architectlin** [comment]
`^[[[root@yuntani-desk stefan]# dnf upgrade 
Last metadata expiration check: 0:00:07 ago on Thu 17 Nov 2022 08:41:12 PM CET.
Dependencies resolved.

 Problem 1: package obs-studio-libs-28.1.2-1.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.6, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.7-1.fc37.x86_64 and qt5-qtbase-5.15.6-1.fc37.x86_64
  - cannot install the best update candidate for package qt5-qtbase-5.15.6-1.fc37.x86_64
  - cannot install the best update candidate for package obs-studio-libs-28.1.2-1.fc37.x86_64
 Problem 2: package obs-studio-28.1.2-1.fc37.x86_64 requires libobs-frontend-api.so.0()(64bit), but none of the providers can be installed
  - package obs-studio-28.1.2-1.fc37.x86_64 requires libobs.so.0()(64bit), but none of the providers can be installed
  - package obs-studio-28.1.2-1.fc37.x86_64 requires obs-studio-libs(x86-64) = 28.1.2-1.fc37, but none of the providers can be installed
  - package obs-studio-libs-28.1.2-1.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.6, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.7-1.fc37.x86_64 and qt5-qtbase-5.15.6-1.fc37.x86_64
  - package python3-qt5-base-5.15.6-9.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.7, but none of the providers can be installed
  - cannot install the best update candidate for package python3-qt5-base-5.15.6-8.fc37.x86_64
  - cannot install the best update candidate for package obs-studio-28.1.2-1.fc37.x86_64
 Problem 3: problem with installed package obs-studio-libs-28.1.2-1.fc37.x86_64
  - package obs-studio-libs-28.1.2-1.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.6, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.7-1.fc37.x86_64 and qt5-qtbase-5.15.6-1.fc37.x86_64
  - package qt5-qdbusviewer-5.15.7-1.fc37.x86_64 requires qt5-qtbase(x86-64) >= 5.15.7, but none of the providers can be installed
  - cannot install the best update candidate for package qt5-qdbusviewer-5.15.6-1.fc37.x86_64
 Problem 4: problem with installed package obs-studio-28.1.2-1.fc37.x86_64
  - package obs-studio-28.1.2-1.fc37.x86_64 requires libobs-frontend-api.so.0()(64bit), but none of the providers can be installed
  - package obs-studio-28.1.2-1.fc37.x86_64 requires libobs.so.0()(64bit), but none of the providers can be installed
  - package obs-studio-28.1.2-1.fc37.x86_64 requires obs-studio-libs(x86-64) = 28.1.2-1.fc37, but none of the providers can be installed
  - package obs-studio-libs-28.1.2-1.fc37.x86_64 requires qt5-qtbase(x86-64) = 5.15.6, but none of the providers can be installed
  - package qt5-qtbase-5.15.6-1.fc37.x86_64 requires qt5-qtbase-common = 5.15.6-1.fc37, but none of the providers can be installed
  - cannot install both qt5-qtbase-common-5.15.7-1.fc37.noarch and qt5-qtbase-common-5.15.6-1.fc37.noarch
  - cannot install the best update candidate for package qt5-qtbase-common-5.15.6-1.fc37.noarch
==========================================================================================================================================================================================
 Package                                            Architecture                            Version                                        Repository                                Size
==========================================================================================================================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 qt5-qtbase                                         x86_64                                  5.15.7-1.fc37                                  updates                                  3.6 M
 qt5-qtbase-common                                  noarch                                  5.15.7-1.fc37                                  updates                                   12 k
Skipping packages with broken dependencies:
 python3-qt5-base                                   x86_64                                  5.15.6-9.fc37                                  updates                                  3.3 M
 qt5-qdbusviewer                                    x86_64                                  5.15.7-1.fc37                                  updates                                   56 k

Transaction Summary
==========================================================================================================================================================================================
Skip  4 Packages

Nothing to do.
Complete!
[root@yuntani-desk stefan]# dnf upgrade --best --allowerasing
Last metadata expiration check: 0:00:14 ago on Thu 17 Nov 2022 08:41:12 PM CET.
Error: 
 Problem: The operation would result in removing the following protected packages: plasma-desktop
(try to add '--skip-broken' to skip uninstallable packages)
`

**Comment by g6avk** [comment]
FWIW qt5-qtwebengine-freeworld has been rebuilt and is queued for testing.

https://koji.rpmfusion.org/koji/buildinfo?buildID=24158 

I didn't have this issue due to not having the freeworld version installed :)

**Comment by ZaWertun** [comment]
Now same is issue now happening with `obs-studio`...
New build for `obs-studio` is already built in koji: https://koji.rpmfusion.org/koji/buildinfo?buildID=24154 (Rebuilt due to Qt update).
I'm still suggesting removing this package temporarily and reinstall it after new builds will appear in RPMFusion stable repo.

It's actually happens with almost every update of Qt, RPMFusion packages is not synchronized with Fedora stable repo.

**Comment by architectlin** [comment]
ty 
it was the obs-studio 

> FWIW qt5-qtwebengine-freeworld has been rebuilt and is queued for testing.
> 
> https://koji.rpmfusion.org/koji/buildinfo?buildID=24158
> 
> I didn't have this issue due to not having the freeworld version installed :)
Download Speed     284 kB/s |  45 MB     02:42  https://koji.rpmfusion.org/

really now!!!
