### ISSUE TITLE
Kscreenlocker broken

### ISSUE THREAD

**Issue by architectlin** [ZaWertun/fedora-copr-kde5#152]
The screen locker is broken and unlocking is not possible anymore. In order to unlock switch to a virtual terminal(Ctrl+Alt+F2), login and execute the command loginctl unlock-session 2. Afterwards switch back to the running session (Ctrl+Alt+F1)

`[root@yuntani-desk stefan]# journalctl --since today | grep "locker"
Nov 18 07:55:25 yuntani-desk kscreenlocker_greet[3580]: QSocketNotifier: Can only be used with threads started with QThread
Nov 18 07:55:26 yuntani-desk kscreenlocker_greet[3580]: kf.kirigami: Failed to find a Kirigami platform plugin
Nov 18 07:55:26 yuntani-desk audit[3580]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3580 comm="kscreenlocker_g" exe="/usr/libexec/kscreenlocker_greet" sig=11 res=1
Nov 18 07:55:26 yuntani-desk kernel: kscreenlocker_g[3580]: segfault at 18 ip 00007fb62ad21da6 sp 00007ffd9eab7610 error 4 in libLayerShellQtInterface.so.5.26.3[7fb62ad20000+3000]
Nov 18 07:55:26 yuntani-desk kscreenlocker_greet[3606]: QSocketNotifier: Can only be used with threads started with QThread
Nov 18 07:55:26 yuntani-desk kscreenlocker_greet[3606]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Nov 18 07:55:26 yuntani-desk kscreenlocker_greet[3606]: The Wayland connection experienced a fatal error: Invalid argument
Nov 18 07:55:26 yuntani-desk kscreenlocker_greet[3610]: QSocketNotifier: Can only be used with threads started with QThread
Nov 18 07:55:26 yuntani-desk kscreenlocker_greet[3610]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Nov 18 07:55:26 yuntani-desk kscreenlocker_greet[3610]: The Wayland connection broke. Did the Wayland compositor die?
Nov 18 07:55:26 yuntani-desk kscreenlocker_greet[3614]: QSocketNotifier: Can only be used with threads started with QThread
Nov 18 07:55:26 yuntani-desk kscreenlocker_greet[3614]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Nov 18 07:55:26 yuntani-desk kscreenlocker_greet[3614]: The Wayland connection broke. Did the Wayland compositor die?
Nov 18 13:44:43 yuntani-desk kscreenlocker_greet[11314]: QSocketNotifier: Can only be used with threads started with QThread
Nov 18 13:44:44 yuntani-desk kscreenlocker_greet[11314]: kf.kirigami: Failed to find a Kirigami platform plugin
Nov 18 13:44:44 yuntani-desk kernel: kscreenlocker_g[11314]: segfault at 18 ip 00007f3a6d110da6 sp 00007ffe9bc62590 error 4 in libLayerShellQtInterface.so.5.26.3[7f3a6d10f000+3000]
Nov 18 13:44:44 yuntani-desk audit[11314]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=11314 comm="kscreenlocker_g" exe="/usr/libexec/kscreenlocker_greet" sig=11 res=1
Nov 18 13:44:44 yuntani-desk kscreenlocker_greet[11340]: QSocketNotifier: Can only be used with threads started with QThread
Nov 18 13:44:44 yuntani-desk kscreenlocker_greet[11340]: The Wayland connection experienced a fatal error: Invalid argument
Nov 18 13:44:44 yuntani-desk kscreenlocker_greet[11344]: QSocketNotifier: Can only be used with threads started with QThread
Nov 18 13:44:44 yuntani-desk kscreenlocker_greet[11344]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Nov 18 13:44:44 yuntani-desk kscreenlocker_greet[11344]: The Wayland connection broke. Did the Wayland compositor die?
Nov 18 13:44:44 yuntani-desk kscreenlocker_greet[11348]: QSocketNotifier: Can only be used with threads started with QThread
Nov 18 13:44:44 yuntani-desk kscreenlocker_greet[11348]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Nov 18 13:44:44 yuntani-desk kscreenlocker_greet[11348]: The Wayland connection broke. Did the Wayland compositor die?
`

**Comment by ZaWertun** [comment]
Is it Wayland-only?

**Comment by ZaWertun** [comment]
Looks like this bug: https://bugs.kde.org/show_bug.cgi?id=461123.

**Comment by ZaWertun** [comment]
Try to update, I just rebuild `plasma-workspace` package maybe it will help.

**Comment by architectlin** [comment]
unfortunately no change:(

**Comment by g6avk** [comment]
No help but..
There are a whole bunch of these lock-screen issues and the ones that I have read about so far use Intel graphics either on wayland or X11

https://bugs.kde.org/buglist.cgi?bug_status=__open__&component=general&list_id=2212813&product=kscreenlocker

Here using nVidia, X11 it works fine with the timer or starting the locker with meta+l 
What GFX  do you use, it maybe worth you checking out the above buglist

**Comment by ZaWertun** [comment]
Solved it.
It's because of `layer-shell-qt` wasn't rebuilt after Qt update.

Here is new build: https://copr.fedorainfracloud.org/coprs/build/5047970

**Comment by ZaWertun** [comment]
@architectlin try to update now.
