### ISSUE TITLE
kdeconnect - openssh bug

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#154]
Looks like this patch did not make it into 22.12.1 

https://bugs.kde.org/show_bug.cgi?id=443155

**Comment by ZaWertun** [comment]
Thanks for the info. I'll apply patch immediately.

**Comment by ZaWertun** [comment]
New release with patch: https://copr.fedorainfracloud.org/coprs/build/5205045

**Comment by ZaWertun** [comment]
Damn, forgot to bump build.

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/build/5205057

**Comment by g6avk** [comment]
The new "bump" build fixed it :) 
Thanks very much!
