### ISSUE TITLE
kf5-kcalendarutils package is missing a file

### ISSUE THREAD

**Issue by bugzy** [ZaWertun/fedora-copr-kde5#155]
kf5-kcalendarutils package is missing the /usr/lib64/grantlee/5.2/kcalendar_grantlee_plugin.so file. The result is that calendar invites in kmail are no longer properly displayed.

**Comment by ZaWertun** [comment]
It's moved to `kf5-kcalendarutils-devel` package by a mistake. I'll fix it.

**Comment by ZaWertun** [comment]
New build with fix: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/5231773/.

**Comment by ZaWertun** [comment]
Should be fixed now, try to update.

**Comment by bugzy** [comment]
Updated and things look good. Thanks
