### ISSUE TITLE
Missing KCM component for flatpak permissions in 5.27

### ISSUE THREAD

**Issue by marco-calautti** [ZaWertun/fedora-copr-kde5#157]
Hi, and as usual, thanks a lot for your work. I just updated to Plasma 5.27. However, I cannot find the new flatpak kcm module that allows to edit flatpak apps permissions from kde's system settings. 
Would it be possible to add it?
Here is the package from src.fedoraproject: https://src.fedoraproject.org/rpms/flatpak-kcm

**Comment by ZaWertun** [comment]
Sure, I'll add it ASAP.

**Comment by ZaWertun** [comment]
Build: https://copr.fedorainfracloud.org/coprs/build/5529486

**Comment by ZaWertun** [comment]
Discover build: https://copr.fedorainfracloud.org/coprs/build/5529498

**Comment by marco-calautti** [comment]
Thanks! Everything works fine!
