### ISSUE TITLE
Issues updating

### ISSUE THREAD

**Issue by marco-calautti** [ZaWertun/fedora-copr-kde5#158]
Hi, while updating today, I am getting the following error:
package plasma-desktop-emojier-5.27.0-1.fc37.x86_64 requires plasma-desktop = 5.27.0-1.fc37, but none of the providers can be installed
  - cannot install both plasma-desktop-5.27.0-2.fc37.x86_64 and plasma-desktop-5.27.0-1.fc37.x86_64
  - cannot install the best update candidate for package plasma-desktop-emojier-5.27.0-1.fc37.x86_64
  - cannot install the best update candidate for package plasma-desktop-5.27.0-1.fc37.x86_64

**Comment by ZaWertun** [comment]
Yeah, just fixed it.

**Comment by marco-calautti** [comment]
I still get the following error:

```
package powerdevil-5.27.9-1.fc38.x86_64 from @System requires libddcutil.so.4()(64bit), but none of the providers can be installed
  - cannot install both libddcutil-2.0.0-1.fc38.x86_64 from updates and libddcutil-1.4.1-1.fc38.x86_64 from @System
  - cannot install both libddcutil-2.0.0-1.fc38.x86_64 from updates and libddcutil-1.4.1-1.fc38.x86_64 from fedora
  - cannot install the best update candidate for package powerdevil-5.27.9-1.fc38.x86_64
  - cannot install the best update candidate for package libddcutil-1.4.1-1.fc38.x86_64
```

I tried to uninstall powerdevil, but it says that it cannot do it as it would cause uninstalling plasma-desktop. So, I guess your plasma-desktop relies on a version of powerdevil that in turn relies on a version of libddcutil that the standard fedora repo does not have.

**Comment by marco-calautti** [comment]
Sorry, I posted the problem in the wrong issue. My comments are actually related to the issue #171 you just closed.
