### ISSUE TITLE
FYI Fedora updates has a bug fix in kwin/kscreen fedora 37

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#160]
As the subject say's.

The RHBZ is https://bugzilla.redhat.com/show_bug.cgi?id=2168034 and the kde report 
https://bugs.kde.org/show_bug.cgi?id=465456

I've been testing wayland and have seen this bug now and then. I am not sure if the kscreen update is related to the above bug.

**Comment by ZaWertun** [comment]
Tjlhanks, I'll try to apply patch later today.

**Comment by ZaWertun** [comment]
Build: https://copr.fedorainfracloud.org/coprs/build/5566080

**Comment by g6avk** [comment]
Thanks! 👍🏻
