### ISSUE TITLE
FYI: fedora's updates-testing has a lot of updates/Conflicts

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#161]
As the Subject says, here is the edited dnf output:

Upgrading:
 grantlee-qt5
 kf5-akonadi-calendar
 kf5-akonadi-calendar-devel
 kf5-grantleetheme
 kf5-grantleetheme-devel
 kf5-kcalendarutils
 kf5-kconfigwidgets
 kf5-kconfigwidgets-devel
 kf5-kpimtextedit
 kf5-kpimtextedit-devel
 khelpcenter
 sddm
 sddm-themes
 sddm-x11                               
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 libkworkspace5
 plasma-lookandfeel-fedora
 plasma-workspace
 plasma-workspace-common
Skipping packages with broken dependencies:
 plasma-workspace

**Comment by ZaWertun** [comment]
It`s on Fedora 37 or 38?

**Comment by g6avk** [comment]
Oops, sorry I edited the DNF output too much :-/ 
Fedora 37

**Comment by g6avk** [comment]
Thanks for the rebuilds.. However I just enabled updates-testing and get this error:

Problem: grantlee-qt5-5.2.0-13.fc37.i686 has inferior architecture
  - package kf5-kcalendarutils-22.12.3-5.fc37.x86_64 requires grantlee-qt5(5.2), but none of the providers can be installed
  - cannot install both grantlee-qt5-5.3.1-1.fc37.x86_64 and grantlee-qt5-5.2.0-13.fc37.x86_64
  - cannot install the best update candidate for package kf5-kcalendarutils-22.12.3-5.fc37.x86_64
  - cannot install the best update candidate for package grantlee-qt5-5.2.0-13.fc37.x86_64

Snip..

Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 grantlee-qt5                      x86_64                      5.3.1-1.fc37 

$ rpm -q grantlee-qt5
grantlee-qt5-5.2.0-13.fc37.x86_64

**Comment by ZaWertun** [comment]
I think I should rebuild kf5-kcalendarutils once again after grantlee-qt5 will appear in stable repo.

**Comment by g6avk** [comment]
I just saw your new builds to fix this, all updated fine. 

Thanks very much 👍🏻
