### ISSUE TITLE
FYI: Testing updating to FC37 > FC38, some conflicts

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#163]
I just tried a dry run of an upgrade from FC37 > FC38 and see these conflicts:

Skipping packages with conflicts:

(add '--best --allowerasing' to command line to force their upgrade):
 libkworkspace5                                        x86_64     5.27.3-1.fc38                            copr:copr.fedorainfracloud.org:zawertun:kde        114 k
 libkworkspace5                                        x86_64     5.27.3-5.fc38                            copr:copr.fedorainfracloud.org:zawertun:kde        114 k
 libkworkspace5                                        x86_64     5.27.4-1.fc38                            copr:copr.fedorainfracloud.org:zawertun:kde        114 k
 libkworkspace5                                        x86_64     5.27.4.1-2.fc38                          fedora                                             131 k
 plasma-workspace                                      x86_64     5.27.4.1-2.fc38                          fedora                                              16 M
 qt5-qtbase                                            x86_64     5.15.9-1.fc38                            updates-testing                                    3.5 M
Skipping packages with broken dependencies:
 plasma-workspace                                      x86_64     5.27.3-1.fc38                            copr:copr.fedorainfracloud.org:zawertun:kde         15 M
 plasma-workspace                                      x86_64     5.27.3-5.fc38                            copr:copr.fedorainfracloud.org:zawertun:kde         15 M
 plasma-workspace                                      x86_64     5.27.4-1.fc38                            copr:copr.fedorainfracloud.org:zawertun:kde         15 M
 sddm-breeze-fedora                                    noarch     5.27.3-1.fc38                            copr:copr.fedorainfracloud.org:zawertun:kde        221 k
 sddm-breeze-fedora                                    noarch     5.27.3-5.fc38                            copr:copr.fedorainfracloud.org:zawertun:kde        221 k
 sddm-breeze-fedora                                    noarch     5.27.4-1.fc38                            copr:copr.fedorainfracloud.org:zawertun:kde        221 k

**Comment by ZaWertun** [comment]
New build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/5791052/

**Comment by g6avk** [comment]
Thanks! all is OK now.
