### ISSUE TITLE
Missed Kmail build? F38

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#165]
Kmail, on this box is still @ version 23.04.0

rpm -q kmail
kmail-23.04.0-1.fc38.x86_64

**Comment by ZaWertun** [comment]
Yep, it's missing.

https://copr.fedorainfracloud.org/coprs/build/5917355

**Comment by ZaWertun** [comment]
Should be fine now.

**Comment by g6avk** [comment]
Yep I have just updated. Thanks!
