### ISSUE TITLE
New versions in fedora 38 updates

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#166]
I'm not sure if you want me to continue to report these 🤔 (I seem like the only person)  Anyway, here goes:

gwenview, gwenview-libs, kf5-baloo, kf5-baloo-file, kf5-baloo-libs and kf5-libkexiv2

**Comment by ZaWertun** [comment]
Thanks for the info.
It makes less and less sense to continue this project.
Now Fedora's KDE packages are updated much faster than before.

**Comment by ZaWertun** [comment]
+ https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/6082598/
+ https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/6082640/
+ https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/6082644/

**Comment by g6avk** [comment]
> Thanks for the info. It makes less and less sense to continue this project. Now Fedora's KDE packages are updated much faster than before.

Yes I fully understand, a lot of work and we appreciate you providing the latest Plasma these past years..
