### ISSUE TITLE
Dolphin in your copr repo doesn't have share option in context menu

### ISSUE THREAD

**Issue by pizzadude** [ZaWertun/fedora-copr-kde5#17]
Dolphin in the regular fedora repos has "share" option in the right click menu of a file, with options to share to imgur, kdeconnect device, etc. The build in your copr repo is missing this option. Apparently it uses something called "purpose" which is part of kf5. https://phabricator.kde.org/D13124

**Comment by ZaWertun** [comment]
Can't reproduce on my system...
![image](https://user-images.githubusercontent.com/1080298/69518192-fb46f100-0f67-11ea-875c-fb2c3dac4f4e.png)

**Comment by pizzadude** [comment]
Do you have this menu?
![HD NO LOGO SCE 174](https://user-images.githubusercontent.com/1454420/69518649-18f36680-0f26-11ea-8586-5a40c27ae6ec.png)

**Comment by pizzadude** [comment]
Do you have this menu?
![sharemenukde](https://user-images.githubusercontent.com/1454420/69518695-358f9e80-0f26-11ea-948c-0c995472ba5e.png)

**Comment by ZaWertun** [comment]
Maybe Dolphin has been built without kf5-purpose, I'll check this.

**Comment by ZaWertun** [comment]
kf5-purpose was built without optional build deps, just fixed it: https://github.com/ZaWertun/fedora-copr-kde5/commit/89574d733ddcff2fb2ea3de1845b980e44659605

**Comment by pizzadude** [comment]
Yes, that fixed it. Thank you. Also, the kwin problem was on my end, sorry. I fixed it by restoring from a snapshot of a few days ago, then doing an update.

**Comment by ZaWertun** [comment]
Thanks for reporting!
