### ISSUE TITLE
kmail @ version 23.08.0

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#170]
I have just noticed that kmail is @ version 23.08.0

dnf list --disablerepo=* | grep 23.08.0
kmail.x86_64                                             23.08.0-1.fc38                                copr:copr.fedorainfracloud.org:zawertun:kde
kmail-libs.x86_64                                        23.08.0-1.fc38                                copr:copr.fedorainfracloud.org:zawertun:kde

**Comment by ZaWertun** [comment]
Yes, I know  Rebuilding it now.

**Comment by g6avk** [comment]
Just updated, Thanks very much!
