### ISSUE TITLE
Conflicts when updating

### ISSUE THREAD

**Issue by marco-calautti** [ZaWertun/fedora-copr-kde5#171]
Hi, I am on Fedora 38, and when I try to update I get different conflicts, such as:
`cannot install both plasma-workspace-5.27.9.1-2.fc38.x86_64 from updates and plasma-workspace-5.27.9.1-1.fc38.x86_64 from copr:copr.fedorainfracloud.org:zawertun:kde
`

I guess you need to bump packages version.

**Comment by ZaWertun** [comment]
New build: https://copr.fedorainfracloud.org/coprs/build/6634708

**Comment by ZaWertun** [comment]
Conflict with libddcutil should go away, try to update again.
