### ISSUE TITLE
KDE Frameworks 5.114

### ISSUE THREAD

**Issue by tleepa** [ZaWertun/fedora-copr-kde5#172]
Hi :)

If you don't mind me asking - are you planning to build [KDE Frameworks 5.114](https://kde.org/announcements/frameworks/5/5.114.0/)?

**Comment by ZaWertun** [comment]
https://github.com/ZaWertun/fedora-copr-kde5/commit/6a97ac866fff934ee280cc1645fb039dc9fc6cea

**Comment by ZaWertun** [comment]
I'll try to update.
Let's hope it won't break anything after official Fedora packages would migrate to Qt6.
