### ISSUE TITLE
kwin is broken in this copr in Fedora 31 after updates

### ISSUE THREAD

**Issue by pizzadude** [ZaWertun/fedora-copr-kde5#18]
In Fedora 31 with testing repos enabled, kwin_x11 is broken currently:

It crashes with the following message:

kwin_x11: symbol lookup error: /lib64/libkwin.so.5: undefined symbol: _ZNK10NETWinInfo15gtkFrameExtentsEv

**Comment by ZaWertun** [comment]
Too bad :(
Just started rebuild for kwin & kwin-lowlatency for F31, this should help.
I'm still on Fedora 31...

**Comment by pizzadude** [comment]
Unfortunately even after the kwin rebuild its still broken. :( So for now I will use this copr https://copr.fedorainfracloud.org/coprs/mkyral/plasma-unstable/

**Comment by ZaWertun** [comment]
Don't mixup packages from different repos, you'll got weird errors in the end.

**Comment by pizzadude** [comment]
I'm not mixing up packages, I disable your repo, then do dnf distro-sync.

**Comment by ZaWertun** [comment]
Then it's OK :)

**Comment by ZaWertun** [comment]
Just tried updating my test VM with F31 from my repo - can't see any errors when restarting kwin.

**Comment by pizzadude** [comment]
You're right. I fixed it by restoring from backup.
