### ISSUE TITLE
If you reinstall kf5-kwindowsystem in Fedora 31, it gets downloaded from updates-testing instead of this copr resulting in broken kwin

### ISSUE THREAD

**Issue by pizzadude** [ZaWertun/fedora-copr-kde5#19]
Hi, I found the real reason behind https://github.com/ZaWertun/fedora-copr-kde5/issues/18 .

If you reinstall this copr, which ends up reinstalling kf5-kwindowsystem, and you use Fedora 31 with updates-testing repo, it installs kf5-kwindowsystem without the GTK_FRAME_EXTENTS patch resulting in broken kwin. That's the reason why kwin crashed with "kwin_x11: symbol lookup error: /lib64/libkwin.so.5: undefined symbol: _ZNK10NETWinInfo15gtkFrameExtentsEv".

You can fix it by doing: sudo dnf reinstall --disablerepo updates-testing kf5-kwindowsystem

Maybe put this in the copr repo notes?

**Comment by ZaWertun** [comment]
Damn, that's bad.
I can bump release for kf5-kwindowsystem in my repo (to +100, for example), or I can remove those GTK_FRAME_EXTENTS patches to not break things.
Also updates-testing is disabled by default.

**Comment by pizzadude** [comment]
I know it's disabled by default, but I like to enable it. It will eventually be in the non-testing repo anyways. You can do whichever you want, but if you keep the GTK_FRAME_EXTENTS patch I hope you don't mind me filing a bug whenever it needs a version bump.

**Comment by ZaWertun** [comment]
For now I'll keep release for kf5-kwindowsystem bumped to +100 - https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1119132/. All subsequent updates to this package will also follow this rule.

That means package from my repo will be selected instead of package from `updates`.

One of Fedora drawbacks is that package from official repo can replace package installed from some third party repo.
In openSUSE for example such packages will be tied to repo from which they were installed.

**Comment by pizzadude** [comment]
Thanks. On a semi-related note, if you ever decide to upgrade to Fedora 31 KDE, you should probably know about this bug, just in case you come across it so you aren't confused: https://bugzilla.redhat.com/show_bug.cgi?id=1754395
I came across it during the Fedora 31 beta, and it occurs regardless of if someone is using a KDE copr or not.

**Comment by ZaWertun** [comment]
http://phabricator.kde.org/D24660
Hurray!

**Comment by pizzadude** [comment]
:D Yay!

**Comment by ZaWertun** [comment]
> Thanks. On a semi-related note, if you ever decide to upgrade to Fedora 31 KDE, you should probably know about this bug, just in case you come across it so you aren't confused: https://bugzilla.redhat.com/show_bug.cgi?id=1754395
> I came across it during the Fedora 31 beta, and it occurs regardless of if someone is using a KDE copr or not.

About this bug - you'll need to remove package `Lmod`. After that - do relogin.
I added this information to the bug report.

**Comment by pizzadude** [comment]
Yeah I saw your solution. It worked. Thanks. (I''m the guy who reported that bug)

**Comment by ZaWertun** [comment]
I'm closing issue - GTK_FRAME_EXTENTS support has been merged to kf5-kwindowsystem-5.65.0.
The patch is no longer needed.
