### ISSUE TITLE
Will not boot to SDDM with Qt 5.12.4

### ISSUE THREAD

**Issue by ayhc** [ZaWertun/fedora-copr-kde5#2]
Installed Qt 5.12.4 packages from Fedora 30 updates-testing (F30 is currently on Qt 5.12.1).

Expected behavior: boots to SDDM and KDE as normal.

Actual behavior: booting process freezes before login screen.

Further notes: Tried Plasma 5.16.2 packages from another COPR repo that appear to have been compiled against Qt 5.12.4, and they work without incident.

**Comment by ZaWertun** [comment]
Dnf warns about private API changes in Qt-5.12.4 and forbids updates.
Wait when qt-5.12.4 will be available in stable I will rebuild required packages.

There is list:
xdg-desktop-portal-kde - libQt5PrintSupport.so.5(Qt_5.12.1_PRIVATE_API)
plasma-integration - libQt5Gui.so.5(Qt_5.12.1_PRIVATE_API)
kwin-wayland - libQt5Core.so.5(Qt_5.12.1_PRIVATE_API)
kwin-libs - libQt5Gui.so.5(Qt_5.12.1_PRIVATE_API)

**Comment by ayhc** [comment]
Great, thanks. Will close issue.
