### ISSUE TITLE
Online Accounts Error loading QML file

### ISSUE THREAD

**Issue by architectlin** [ZaWertun/fedora-copr-kde5#20]
Problem with the last update see screen shot
![Screenshot_20191216_122354](https://user-images.githubusercontent.com/58938927/70903684-ad218c80-1fff-11ea-9774-d3eddbc81bba.png)

**Comment by ZaWertun** [comment]
It looks like now we need this package - https://code.launchpad.net/~online-accounts/accounts-qml-module/trunk to get KDE Accounts working...

**Comment by architectlin** [comment]
all packages for kde have been installed
which package has to be installed?
here still error message

`Dez 16 14:07:34 laptop.orgiae-6 systemsettings5[7061]: org.kde.kcoreaddons: Error loading plugin "kcm_kaccounts" "The shared library was not found." 
                                                       Plugin search paths are ("/usr/lib64/qt5/plugins", "/usr/bin") 
                                                       The environment variable QT_PLUGIN_PATH might be not correctly set
Dez 16 14:07:34 laptop.orgiae-6 systemsettings5[7061]: "file:///usr/share/kpackage/kcms/kcm_kaccounts/contents/ui/Accounts.qml" 
                                                        "Error loading QML file.\n31: module \"Ubuntu.OnlineAccounts\" is not installed\n"
Dez 16 14:07:34 laptop.orgiae-6 systemsettings5[7061]: <Unknown File>:7: TypeError: Type error
`

**Comment by ZaWertun** [comment]
This package was Ubuntu-only and is absent in Fedora repos.
I'll build it in my kde copr, then I'll add it as dependency to the `kaccounts-integration` package.

**Comment by architectlin** [comment]
kaccounts-integration is installed,
a new installation of the package has not been successful

**Comment by ZaWertun** [comment]
Just do `sudo dnf update --refresh`.

**Comment by architectlin** [comment]
OK now there were 2 packages for the update;)
accounts-qml-module-0.6+17.04.20170405-1.fc31.x86_64
and
kaccounts-providers-19.12.0-2.fc31.x86_64  

what can I say thank you_ :)
now it works:)

**Comment by vigne** [comment]
Hello,

apologies for reviving this thread, but I have the very same error using Fedora 31 and running kaccounts-(provider/integrations) 19.12.1. I tried to understand the solution you provided above but it seems I'm missing something basic here.

> I'll build it in my kde copr, then I'll add it as dependency to the `kaccounts-integration` package.

What does this mean? Maybe you could explain it a bit more detailed how to make accounts-qml-module appear in Fedora 31?

Cheers

**Comment by ZaWertun** [comment]
@vigne Just build the package `accounts-qml-module` & install it in the system.
After that kaccounts-integration will be fixed.

**Comment by posercorpse** [comment]
> @vigne Just build the package `accounts-qml-module` (https://github.com/ZaWertun/fedora-copr-kde5/blob/master/accounts-qml-module/accounts-qml-module.spec) & install it in the system.
> After that kaccounts-integration will be fixed.

I'm sorry but I'm an idiot. I tried "building" the spec (I'm very new to this) but keep getting presented with an error regarding a tar.gz file not existing after cloning. Am I missing something here??

**Comment by ZaWertun** [comment]
> > @vigne Just build the package `accounts-qml-module` (https://github.com/ZaWertun/fedora-copr-kde5/blob/master/accounts-qml-module/accounts-qml-module.spec) & install it in the system.
> > After that kaccounts-integration will be fixed.
> > @ZaWertun
> > I'm sorry but I'm an idiot. I tried "building" the spec (I'm very new to this) but keep getting pre@sented with an error regarding a tar.gz file not existing after cloning. Am I missing something here??

You have to download sources for package.
Run this command inside directory with spec file:
`spectool -g *.spec`
