### ISSUE TITLE
Missed packages ?

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#22]
Hi,

I have had a notification for some kf5 package updates from Fedora's repos.
Are some packages missing from your 5.66 update.
kf5-krunner
kf5-attica
kf5-kfilemetadata
I think also there was an update to kaccounts-providers for some Google issues, but not for the Gmail issues.

**Comment by ZaWertun** [comment]
Damn, something goes wrong with last update...
I'll submit those builds.

**Comment by ZaWertun** [comment]
kf5-attica and kf5-kfilemetadata are already built:
1. https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1143322/
2. https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1143271/

**Comment by ZaWertun** [comment]
Build for kf5-krunner is ready - https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1171827/.

**Comment by g6avk** [comment]
Thanks, kf5-krunner updated fine.
kf5-attica and kf5-kfilemetadata are newer > to 5.66.0-2 from the Fedora Repo

**Comment by ZaWertun** [comment]
Wait, where did you get kf5-attica-5.66?
Fedora 31 has only version 5.64 in it's repos.

**Comment by ZaWertun** [comment]
Done.
kf5-attica-5.66.0-3 - https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1176798/
kf5-kfilemetadata-5.66.0-3 - https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1176799/

**Comment by g6avk** [comment]
5.66 was in updates-testing, I cherry pick what packages to test from testing :-)
Thanks for your kf5-attica and kf5-kfilemetadata updates all installed fine, I'll close this now.
