### ISSUE TITLE
KDE 5.18 Telemetry (user feedback) setting missing

### ISSUE THREAD

**Issue by pizzadude** [ZaWertun/fedora-copr-kde5#23]
I noticed that there is no user feedback setting in plasma settings in your copr build. Is this because it isn't built? If so, does this mean it's disabled?

**Comment by ZaWertun** [comment]
Just building package for it - kuserfeedback-1.0.0

**Comment by pizzadude** [comment]
Thanks

**Comment by pizzadude** [comment]
That package doesn't provide the system settings page.

**Comment by ZaWertun** [comment]
It's just dependency. 
After building that package `plasma-workspace` must be rebuilded.
Wait for this build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1237270/.

**Comment by ZaWertun** [comment]
Build is ready you can now run `sudo dnf update --refresh`.

**Comment by pizzadude** [comment]
Confirmed fixed. Thanks.
