### ISSUE TITLE
Cannot unlock widgets 5.18

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#24]
Just noticed I cannot unlock widgets,
I found the bug report + commit info for the fix:

https://bugs.kde.org/show_bug.cgi?id=417424

**Comment by ZaWertun** [comment]
Thanks!
Patch was applied in this build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1237759/

**Comment by g6avk** [comment]
Great! widgets are now unlocked and "customise Layout" is not greyed out and works great.

I am puzzled why the Devs have removed the lock widgets option though, however they can be locked via the CLI.. hmm
Thanks providing the latest kde for Fedora.
