### ISSUE TITLE
Just a heads up

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#26]
I noticed there is a new version update/bump for kf5-knewstuff and kf5-kirigami2 in updates-testing.
Just FYI this version of knewstuff will break some widgets, like weather.
As we all know it is not good to mix repo's

**Comment by ZaWertun** [comment]
As soon as Fedora KDE team starts doing regular updates - there is little sense in my separate repo.

**Comment by ZaWertun** [comment]
Also last time packages was broken because of new Qt version in updates-testing.
Everything should be fine now.

**Comment by g6avk** [comment]
It is only recently (and **not** often due to time restrictions Rex has) Fedora KDE catches up, especially with Applications.
My comment was just for **info** in case anyone else reported issues.

FYI I use updates-testing and Bodhi to help test and try and help Fedora (mainly kernel)
The work you do supporting KDE for Fedora is most appreciated.

Thanks!
