### ISSUE TITLE
Blank Site Online Accounts

### ISSUE THREAD

**Issue by architectlin** [ZaWertun/fedora-copr-kde5#27]
Problem Open Online Accounts 
Klick add new Accounts
Site is blank
![Screenshot_20200227_163918](https://user-images.githubusercontent.com/58938927/75537338-1f0e4d00-5a17-11ea-8d0a-68f98543a31f.png)

**Comment by ZaWertun** [comment]
Hi.
Please run `kcmshell5 kcm_kaccounts` in the console and show output.

**Comment by ZaWertun** [comment]
You need to install package `kaccounts-providers`.
I'll add this package as dependency for `plasma-systemsettings`.

**Comment by architectlin** [comment]
my fehler neu install läßt grussen 
kannst schliesen 
thx

**Comment by ZaWertun** [comment]
Update of `plasma-systemsettings` with a fix: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1259324/.
