### ISSUE TITLE
No Kmail 20.04

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#29]
Hi,
Just went to update applications on this F31 box and dnf reports "nothing provides kmail >= 20.04 needed by kontact-20.04.0-1.fc31.x86_64"

**Comment by ZaWertun** [comment]
Damn.
Somehow it wasn't built.
I'll build it now, just wait a little.

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1347798/

**Comment by ZaWertun** [comment]
Done.

**Comment by g6avk** [comment]
Thanks, all update fine.

Thanks!
