### ISSUE TITLE
kwin-lowlatency wants to downgrade other packages

### ISSUE THREAD

**Issue by luminoso** [ZaWertun/fedora-copr-kde5#3]
I'm running Fedora 30 x86_64 fully updated.

1. dnf copr enable zawertun/kde && dnf update --refresh

System got updated to plasma 5.16.2.

> dnf list installed | grep 5.15

Doesn't show anything

> dnf list installed | grep 5.16

shows packages coming from repo @zawertun-kde

However when I try:
> dnf install --allowerasing kwin-lowlatency

it wants to downgrade plasma in order to install kwin-lowlatency
![image](https://user-images.githubusercontent.com/296323/60878987-b2043800-a238-11e9-9144-0a1fe508472f.png)

I don't think this is expected?

**Comment by ZaWertun** [comment]
Hello!

I've got this bug too :)
Steps to get around the bug:
1. `dnf install --allowerasing kwin-lowlatency`
2. `dnf update --refresh`

After 2 step dnf will update all plasma packages to the latest in my repo.
Further updates of kwin-lowlatency will occur without problems (already checked it).

Don't know why dnf doing that, maybe some sort of bug in dnf 🤔

**Comment by ZaWertun** [comment]
I'll update docs in the copr.

**Comment by luminoso** [comment]
Yes that solved the issue to me also. What DNF did wast downgrade packages to install kwin-lowlatency and then with command 2 it re-updated them.

Thank you for maintaining this. I wasn't expected such a difference with kwin-lowlatency. Truly awesome. Hope it get to the upstream soon 🤞

**Comment by luminoso** [comment]
The docs in copr are not totally correct. Where you updated:

```
1. sudo dnf install --allowerasing kwin-lowlatency
2. dnf update --refresh - on this step dnf will upgrade all packages that was downgraded on step 1 (dnf bug?)
3. kwin_x11 --replace &
```

Should be read:

```
1. dnf update --refresh
1. sudo dnf install --allowerasing kwin-lowlatency  - on this step dnf will upgrade all packages that was downgraded on step 1 (dnf bug?)
2. dnf update --refresh 
3. kwin_x11 --replace &
```

If you do `sudo dnf install --allowerasing kwin-lowlatency` before the update it will install _kwin-lowlatency-5.16.x_ instead of _kwin-lowlatency-5.15.x_. Because fedora 30 is currently on 5.15 and it will break plasma and the user cannot re-login into the session!

The user should update all _plasmadesktop_ to 5.16.x first, then replace _kwin_ and then re-update downgraded plasma packages. Preferably in one shot, like this:

```
1. dnf update --refresh
1. sudo dnf install --allowerasing kwin-lowlatency  && dnf update --refresh -y
3. kwin_x11 --replace &
```

**Comment by ZaWertun** [comment]
You right, I'll update instructions.
Thanks for the feedback!
