### ISSUE TITLE
kf5-ktexteditor and libgit2 dependency conflict in Fedora 32

### ISSUE THREAD

**Issue by pizzadude** [ZaWertun/fedora-copr-kde5#30]
In Fedora 32, with testing repos enabled, there is this error with dnf update:
```
  - problem with installed package kf5-ktexteditor-5.69.0-1.fc32.x86_64
  - package kf5-ktexteditor-5.69.0-1.fc32.x86_64 requires libgit2.so.0.99()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package libgit2-0.99.0-2.fc32.x86_64
  - cannot install both libgit2-1.0.0-1.fc32.x86_64 and libgit2-0.99.0-2.fc32.x86_64
  - cannot install both libgit2-0.99.0-2.fc32.x86_64 and libgit2-1.0.0-1.fc32.x86_64`
```
Caused by this update: https://bodhi.fedoraproject.org/updates/FEDORA-2020-cb72ecb134 (which will soon land in the stable repos)
kf5-ktexteditor needs to be rebuilt to work with new libgit2. Currently, I can't update libgit2 because of kf5-ktexteditor.

**Comment by ZaWertun** [comment]
Just added build in `kde-testing` repo: https://copr.fedorainfracloud.org/coprs/zawertun/kde-testing/build/1352920/.
As soon as libgit2 has been moved to stable I'll also rebuild it in `kde` repo.

**Comment by ZaWertun** [comment]
Other build: https://copr.fedorainfracloud.org/coprs/zawertun/kde-testing/build/1352931/.

**Comment by ZaWertun** [comment]
This build should be fine: https://copr.fedorainfracloud.org/coprs/zawertun/kde-testing/build/1352935/.

**Comment by pizzadude** [comment]
Thank you.
