### ISSUE TITLE
kde-connect bluetooth

### ISSUE THREAD

**Issue by bugzy** [ZaWertun/fedora-copr-kde5#31]
Looking at the spec, I cannot tell if kde-coonect in this repo built with bluetooth support. Can you clarify? If it is not it looks like it can be enabled by installing a certain framework package.

Thanks

**Comment by ZaWertun** [comment]
Now it's built without Bluetooth support. I'll try to enable it.
You also need special version of the android application if you want connection over Bluetooth.

**Comment by ZaWertun** [comment]
Commit: 369a28660df140d01ccaee1126aba062ff682705
New build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1372800/

**Comment by bugzy** [comment]
Excellent! Thanks.

Someone made that "special version" of the application here: 
https://www.reddit.com/r/kde/comments/ga911b/anyone_wants_to_try_out_kdeconnect_over_bluetooth/
