### ISSUE TITLE
Backport fix for https://bugs.kde.org/show_bug.cgi?id=421374

### ISSUE THREAD

**Issue by pizzadude** [ZaWertun/fedora-copr-kde5#34]
Is it possible you can backport the fix for https://bugs.kde.org/show_bug.cgi?id=421374 ?
Thanks

**Comment by ZaWertun** [comment]
No problem - I'll add patch to fix this bug.

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1428285/

**Comment by ZaWertun** [comment]
173bf72dc343ca69c6ac1c457d906472f61f5403

**Comment by pizzadude** [comment]
Thanks for backporting.

I had to do " sudo dnf reinstall --disablerepo=updates kf5-kio* " due to the version number being the same as the kf5-kio packages from the fedora updates repo, then it grabbed the packages from your copr.

Fix confirmed working. :)

**Comment by ZaWertun** [comment]
Sorry, forgot bump revision again. 1 sec.

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1428303/

**Comment by pizzadude** [comment]
All good now. Thanks.
