### ISSUE TITLE
Plasma-5.19 can't be built - qt-5.14 is not available for F32

### ISSUE THREAD

**Issue by ZaWertun** [ZaWertun/fedora-copr-kde5#35]
While Plasma-5.19 requires Qt-5.14 Fedora 32 still doesn't have it.
We will wait for a bright future.

**Comment by architectlin** [comment]
Qt-5.14 can only be found in the Fedora Updates Testing x86_64 
[](https://pkgs.org/search/?q=qt5-qtbase-)

**Comment by ZaWertun** [comment]
@architectlin Can't find it at https://bodhi.fedoraproject.org/ (https://bodhi.fedoraproject.org/updates/?search=&status=testing&releases=F32&page=1).

**Comment by ZaWertun** [comment]
Just find it: https://bodhi.fedoraproject.org/updates/FEDORA-2020-c80eec2ce4 :)

**Comment by pizzadude** [comment]
It's now stable. :D

**Comment by ZaWertun** [comment]
90c4af08b2e359d8a4480d672795bd53f3d6e8cd

**Comment by pizzadude** [comment]
@ZaWertun Looks good, but in your build "ksystemstats" doesn't start with plasma which is needed for the system monitor, network monitor widgets, etc widgets so the user has to manually add it to startup.

**Comment by architectlin** [comment]
system monitor, network monitor, etc widgets have no function with me

**Comment by pizzadude** [comment]
@architectlin For now, add "ksystemstats" to startup.

**Comment by architectlin** [comment]
> @architectlin For now, add "ksystemstats" to startup. That fixes it.

how do you mean add that exactly where'?

**Comment by pizzadude** [comment]
![image](https://user-images.githubusercontent.com/1454420/84804566-f95e8100-afd0-11ea-8581-503492d4a071.png)
@architectlin

**Comment by ZaWertun** [comment]
Oops, closed to soon...

**Comment by ZaWertun** [comment]
> system monitor, network monitor, etc widgets have no function with me
> kde 5.19.1 are available https://kde.org/announcements/plasma-5.19.1

I see similar bugs in he KDE bug tracker - it must be fixed in 5.19.1.

**Comment by ZaWertun** [comment]
Also there is DBUS service for ksystemstats, so it must activate automatically. (/usr/share/dbus-1/services/org.kde.ksystemstats.service)

**Comment by ZaWertun** [comment]
https://invent.kde.org/plasma/libksysguard/commit/27da06df3abaf707d61686e3a301a84df7b099c8 :)

**Comment by ZaWertun** [comment]
@pizzadude, @architectlin try to update to plasma-5.19.1. I just built it.

**Comment by pizzadude** [comment]
Confirmed fixed. Thanks.
Note to @architectlin, if you did my temporary workaround, you should remove it after upgrading to 5.19.1

**Comment by architectlin** [comment]
upgrade went through to 5.19.1 
so far it all seems to be going well.

**Comment by ZaWertun** [comment]
Nice.

**Comment by pizzadude** [comment]
One thing I noticed, is the "Sensors Details" section of the system monitor widgets configuration doesn't work, and in terminal it shows this

file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:300:25: QML StackView: replace: file:///usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/ui/config/ConfigSensors.qml:30 module "org.kde.kitemmodels" is not installed

**Comment by ZaWertun** [comment]
> One thing I noticed, is the "Sensors Details" section of the system monitor widgets configuration doesn't work, and in terminal it shows this
> 
> file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:300:25: QML StackView: replace: file:///usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/ui/config/ConfigSensors.qml:30 module "org.kde.kitemmodels" is not installed

Try to install `kf5-kitemmodels`.

**Comment by pizzadude** [comment]
It is installed.

**Comment by pizzadude** [comment]
( Btw, if you can't fix it, it's not an issue for me, as I don't need that setting. I just thought it would be a good idea to point it out )

**Comment by ZaWertun** [comment]
> ( Btw, if you can't fix it, it's not an issue for me, as I don't need that setting. I just thought it would be a good idea to point it out )

Found it! Package `kf5-kitemmodels` must be build with optional dependency `cmake(Qt5Qml)`.
And then we'll get `libitemmodelsplugin.so`.

**Comment by pizzadude** [comment]
Nice!

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1469065/

**Comment by pizzadude** [comment]
Still an issue. Must be a KDE bug.

**Comment by architectlin** [comment]
I was just about to write
but now with the upgrade of kf5-kitemmodels it works

**Comment by ZaWertun** [comment]
> Still an issue. Must be a KDE bug.

Works for me too after update. Could you try one more time ?

**Comment by pizzadude** [comment]
Here's a GIF of the problem.
![Peek 2020-06-16 18-06](https://user-images.githubusercontent.com/1454420/84833011-558aca80-affc-11ea-9853-31ce9c2bdf5f.gif)

**Comment by pizzadude** [comment]
rpm -q --list kf5-kitemmodels
/usr/lib/.build-id
/usr/lib/.build-id/15
/usr/lib/.build-id/15/1ae15a1f8f383368d59b7b867fdcb34321ca5d
/usr/lib64/libKF5ItemModels.so.5
/usr/lib64/libKF5ItemModels.so.5.71.0
/usr/share/doc/kf5-kitemmodels
/usr/share/doc/kf5-kitemmodels/README.md
/usr/share/licenses/kf5-kitemmodels
/usr/share/licenses/kf5-kitemmodels/COPYING.LIB
/usr/share/qlogging-categories5/kitemmodels.categories

There is no "libitemmodelsplugin.so"

rpm -q --last kf5-kitemmodels
kf5-kitemmodels-5.71.0-2.fc32.x86_64

**Comment by pizzadude** [comment]
Oh wait, nevermind. I'm supposed to install "kf5-kitemmodels-devel".

Then it worked.

**Comment by ZaWertun** [comment]
Damn, those files has been added to the `kf5-kitemmodels-devel` package.
I'll fix this tomorrow.

**Comment by pizzadude** [comment]
Thank you for your hard work.

**Comment by architectlin** [comment]
no problem with gif for kf5-kitemmodels-5.71.0-3.fc32 Thanks
