### ISSUE TITLE
Kwin rules cannot be opened / qml error

### ISSUE THREAD

**Issue by slartibart70** [ZaWertun/fedora-copr-kde5#36]
Hi,
im trying to edit window rules, e.g. by selecting "configure special windows settings" on the window titlebar. Expected result would be the rule-editor, but nothing happens.

So, i tried calling this instead:
kcmshell5 kcm_kwinrules
then adding a new entry or editing an existing entry, which gives a better error message:

`QQmlComponent: Component is not ready
"file:///usr/share/kpackage/kcms/kcm_kwinrules/contents/ui/RulesEditor.qml" 
 "Error loading QML file.\n42: Type RuleItemDelegate unavailable\n63: Type OptionsComboBox unavailable\n32: \"QQC2.ComboBox.valueRole\" is not available due to component versioning.\n"
QCoreApplication::postEvent: Unexpected null receiver
QQmlComponent: Component is not ready
"file:///usr/share/kpackage/kcms/kcm_kwinrules/contents/ui/RulesEditor.qml" 
 "Error loading QML file.\n42: Type RuleItemDelegate unavailable\n63: Type OptionsComboBox unavailable\n32: \"QQC2.ComboBox.valueRole\" is not available due to component versioning.\n"
QCoreApplication::postEvent: Unexpected null receiver`

Is this something caused by the new plasma 5.19 release you can fix or is this a general plasma problem?

(i also have this problem still pending in bugtracker: https://bugs.kde.org/show_bug.cgi?id=421178
is this related to zawertun repos?)

Any help is appreciated

**Comment by ZaWertun** [comment]
Just another bug in the plasma-5.19.
Quick fix - comment line `valueRole: "value"` in the file `/usr/share/kpackage/kcms/kcm_kwinrules/contents/ui/OptionsComboBox.qml`.

**Comment by ZaWertun** [comment]
I.e. change
```qml
    valueRole: "value"
```
to
```qml
//    valueRole: "value"
```

**Comment by ZaWertun** [comment]
I'll try to rebuild `qqc2-desktop-style` with new Qt - maybe it will help.

**Comment by ZaWertun** [comment]
https://github.com/KDE/kwin/commit/a158d3cbd3f997480c483900ac6a35aca6475fb0

**Comment by ZaWertun** [comment]
Update to `qqc2-desktop-style-5.71.0-2.fc32.x86_64` helps - issue is gone.

**Comment by ZaWertun** [comment]
> (i also have this problem still pending in bugtracker: https://bugs.kde.org/show_bug.cgi?id=421178
> is this related to zawertun repos?)

About this bug - it's definitely bug in the code. This patch fixes it:
```patch
diff -r -U3 kwalletmanager-20.04.2.orig/src/konfigurator/konfigurator.cpp kwalletmanager-20.04.2/src/konfigurator/konfigurator.cpp
--- kwalletmanager-20.04.2.orig/src/konfigurator/konfigurator.cpp       2020-06-08 20:54:56.000000000 +0300
+++ kwalletmanager-20.04.2/src/konfigurator/konfigurator.cpp    2020-06-18 15:31:43.467958411 +0300
@@ -176,7 +176,7 @@
 void KWalletConfig::launchManager()
 {
     if (!QDBusConnection::sessionBus().interface()->isServiceRegistered(QStringLiteral("org.kde.kwalletmanager5"))) {
-        QProcess::startDetached(QStringLiteral("kwalletmanager5 --show"), QStringList());
+        QProcess::startDetached(QStringLiteral("kwalletmanager5"), {QStringLiteral("--show")});
     } else {
         QDBusInterface kwalletd(QStringLiteral("org.kde.kwalletmanager5"), QStringLiteral("/kwalletmanager5/MainWindow_1"));
         kwalletd.call(QStringLiteral("show"));
```
It tries to start process `kwalletmanager5 --show`, lold.

**Comment by pizzadude** [comment]
I was having the same issue and it's fixed now after the update. Thanks :)
