### ISSUE TITLE
activity switcher and activity shortcut assignment broken

### ISSUE THREAD

**Issue by slartibart70** [ZaWertun/fedora-copr-kde5#38]
Hi,
i (accidentially) used the meta-tab shortcut which brings up the activity switcher (similar to task-switcher, but containing only one - the default- activity)
Problem ist, it (the newly drawn sidebar) won't go away?
The only option is to log-out and re-login again, a 'kwin_x11 --replace &' also won't help 

Then i decided to get rid of the shortcut assignment in systemsettings5 > workspace behavior > activities > Tab: switching.
There you can reassign or just disable the shortcuts, but i would expect the 'apply' button to become active after a change. Instead, the reassignment works instantly, no apply needed (and, no going back to the previous state, obviously)

any ideas how to fix that?

there is a bugticket already here: https://bugs.kde.org/show_bug.cgi?id=422957

**Comment by ZaWertun** [comment]
Found same bug but more older: https://bugs.kde.org/show_bug.cgi?id=389771.

**Comment by ZaWertun** [comment]
Workaround: you can hide this bar when fast pressing `Meta + Tab` (~0.1 sec.).

**Comment by ZaWertun** [comment]
For me `Esc` is also working to hide this panel.
Could you test it?

**Comment by slartibart70** [comment]
i tried various meta/esc/alt whatever keypresses, slowly/fast.. didn't matter. The only way to get rid of the sidebar was to end the session and logout.
(and, of course, disabling the shortcuts - for me, activities never made sense)

**Comment by ZaWertun** [comment]
100% working workaround: `plasmashell --replace& disown`.
It's some bug in the plasmoid so you need to restart plasma. KWin restart can do nothing with it.

**Comment by ZaWertun** [comment]
Try to update plasma-desktop to version 5.19.2-2.fc32. It may help.

**Comment by slartibart70** [comment]
yes, works nicely now.
Closing this ticket
