### ISSUE TITLE
Refresh repository in one-shot

### ISSUE THREAD

**Issue by luminoso** [ZaWertun/fedora-copr-kde5#4]
Hi.
I've enabled this repo just a week ago, and I could be wrong, but it looks like the repository information metadata is refreshing and updating after each successful build.

This means that if a single kf5-* package is built sucessfuly, then it will trigger an update to anyone using zawertun/kde copr. Update a single package from a major release can potentially break the whole KDE (desktop, applications or frameworks) installation.

My suggestion is that Copr repository metadata should be refreshed only after all the packages of the update are built successfully so that when someone is updating its system it doesn't lead to version inconsistencies, and update the system only when every package for an update is compiled and ready for update

**Comment by ZaWertun** [comment]
Thanks for the suggestion, it will be better that way.
![изображение](https://user-images.githubusercontent.com/1080298/61206448-453ae300-a6fb-11e9-98f7-0b73f5d8c7ae.png)
Done.
