### ISSUE TITLE
Updating to 20.08 fails with conflicting files

### ISSUE THREAD

**Issue by JuneWhitmore** [ZaWertun/fedora-copr-kde5#42]
I'm getting this:

file /usr/lib64/qt5/plugins/kcm_ldap.so from install of kdepim-runtime-libs-1:20.08.0-1.fc32.x86_64 conflicts with file from package kf5-libkdepim-20.04.3-1.fc32.x86_64
file /usr/share/kservices5/kcmldap.desktop from install of kdepim-runtime-1:20.08.0-1.fc32.x86_64 conflicts with file from package kf5-libkdepim-20.04.3-1.fc32.x86_64

**Comment by ZaWertun** [comment]
Could you try running `dnf update --best --allowerasing` instead of regular `dnf update`?

**Comment by JuneWhitmore** [comment]
That works.
"Removing dependent packages: kf5-libkdepim-akonadi"

**Comment by ZaWertun** [comment]
> That works.
> "Removing dependent packages: kf5-libkdepim-akonadi"

Yep. This package was gone in KDE apps 20.08.0.

Maybe I need to add `Obseletes: kf5-libkdepim-akonadi` for `kf5-libkdepim` spec, don't know exactly.

**Comment by JuneWhitmore** [comment]
Thank you!
