### ISSUE TITLE
kde 5.20 clipper

### ISSUE THREAD

**Issue by architectlin** [ZaWertun/fedora-copr-kde5#46]
![Screenshot_20201015_152422](https://user-images.githubusercontent.com/58938927/96132922-15305000-0efb-11eb-9406-672b6e3e2b6a.png)
Fehler beim Laden der QML-Datei: file:///usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/clipboard.qml:110:13: Type BarcodePage unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/BarcodePage.qml:27:1: module "org.kde.prison" is not installed

Installed packages
kf5-prison.x86_64             5.75.0-1.fc33 @copr:copr.fedorainfracloud.org:

**Comment by ZaWertun** [comment]
Thanks for feedback!
Looks like `kf5-prison` must be rebuilt with `Qt5::Quick` dependency.

**Comment by ZaWertun** [comment]
25e19358384e7705c50a72efb8bbadd8bc3b2e43

**Comment by architectlin** [comment]
can close works after update ty
