### ISSUE TITLE
plasma 5.20.x for fedora32?

### ISSUE THREAD

**Issue by slartibart70** [ZaWertun/fedora-copr-kde5#47]
Hi,
i can see there are packages for fc33, but the latest for fc32 is still 5.19.x
Would you mind checking if the build is enabled for fc32?

A question for kwinft: Any recommendations for kwinft on x11 at the moment?
(esp. in comparison to the kwin-lowlatency?)
Or would you regard this as still 'experimental'?

**Comment by mmcnutt** [comment]
5.20 needs Qt 5.15 minimum, which isnt in the standard fc32 repos. fc33 is effectively done, I'm running it all good, but if you're not comfortable upgrading,  Martin Kyral's copr has a fc32 build when you add his qt5-unstable repo https://copr.fedorainfracloud.org/coprs/mkyral/

kwinft 5.20 seems uninstallable at the moment as it wants to downgrade a bunch of components to 5.19.5, essentially giving you a frankenstein install, I think it might just be a case of rebuilding with the proper dependencies, but I'm not an expert

**Comment by ZaWertun** [comment]
A lot of stuff from official and rpmfusion repo would be broken if someone tries to update to Qt 5.15 on Fedora 32.
(Something like Telegram, CopyQ or any other Qt software dependant on Qt private library).

About kwinft - I'll see what can I do.
