### ISSUE TITLE
Downloading old v5.19 plasma-workspace instead of 5.20 under Fedora 32

### ISSUE THREAD

**Issue by tginiotis-at-work** [ZaWertun/fedora-copr-kde5#48]
After doing:
```
dnf copr enable zawertun/kde 
dnf -y update --refresh
``` 

it downloads the `plasma-workspace 5.19.5-1.fc32` package from the Copr and not the 5.20 one.

This is on Fedora 32.

Any ideas what could be the issue?

**Comment by g6avk** [comment]
I think it is because there is no official Qt 5.15 for F32..
zawertun no doubt can tell you more.

**Comment by tginiotis-at-work** [comment]
Ah, ok then. Of course it does not seem to download any 5.20 packages, not just the plasma-workspace one.

**Comment by ZaWertun** [comment]
Plasma 5.20 requires Qt version >= 5.15, do it's only available on Fedora 33.
You need to upgrade to Fedora 33 to get latest stable plasma version.
