### ISSUE TITLE
kwin consuming 100% on one core / fc33, plasma 5.20

### ISSUE THREAD

**Issue by slartibart70** [ZaWertun/fedora-copr-kde5#49]
Hi,
this happens when i switch to a virtual terminal (ctrl-alt-F2, for example)
As long as the X11 is hidden (vterm on F1) one core goes to 100% for the kwin_x11 process. Going back to graphical gui (ctrl-alt F1) and all is fine again. Easily reproducible
Ever encountered such a thing?
(maybe i should mention i am using an older nvidia card with the nouveau driver on this system)

And... (no, i don't want to push you :)
any progress on the dependencies problem when trying to install kwinft for fedora33/plasma5.20?

**Comment by pizzadude** [comment]
I don't have that issue, but I sometimes have 100% CPU for plasmashell ( or latte-dock in my case) when running games in wine. It doesn't happen all the time though.

Your issue could be a nouveau problem.

To install kwinft do "sudo dnf install kwinft --allowerasing" which might downgrade some packages and then "sudo dnf update --refresh" to upgrade the packages again. I'm using Intel integrated graphics and kwinft is laggy on X11. I think it works better in Wayland. Wayland has its own issues though.

**Comment by ZaWertun** [comment]
Can't say anything good about nouveau.
I've got one old NVidia card still working on the 340.x driver - everything is fine.

Also I don't think kwinft will perform better on such old hardware, it's more about wayland development & testing.

**Comment by slartibart70** [comment]
i installed nvidia 340 driver successfully on the system. But, still the same behavior - 100% cpu on one core for kwin_x11 if you go to a vterm (Ctrl-Alt Fx)
This seems suspicious...

**Comment by ZaWertun** [comment]
> i installed nvidia 340 driver successfully on the system. But, still the same behavior - 100% cpu on one core for kwin_x11 if you go to a vterm (Ctrl-Alt Fx)
> This seems suspicious...
> This is a pretty dump and fresh installation on an older i7/16GB machine. Some customizations to the dotfiles and devtools installation (kernel headers, make, gcc and such). Nothing tweaked besides blacklisting nouveau on kernel cmdline and in modprobe.d

Do you try changing rendering backend?
Try switching between XRender / OpenGL 2.0 (System Settings -> Display and Monitor -> Compositor).
And try to change VSync methods, at least Never / Automatic.

**Comment by slartibart70** [comment]
let's close this issue, i moved on to another laptop.
sometimes you need to dump old hardware
