### ISSUE TITLE
kf5-kwindowsystem & kwin-lowlatency with _GTK_FRAME_EXTENTS support

### ISSUE THREAD

**Issue by ZaWertun** [ZaWertun/fedora-copr-kde5#5]
Just rebuilt packages `kf5-kwindowsystem` and `kwin-lowlatency` with patches from https://github.com/zzag/arch-kwin-gtk-frame-extents (not published yet).

After this patch Gnome apps with CSD (Client Side Decorations) will get normal titles,
that's how gnome-calculator looks after patch:
![изображение](https://user-images.githubusercontent.com/1080298/61381684-1c118280-a8b4-11e9-99bd-f020d6d1831b.png)

Some testing required. @luminoso could you test it?

How to install:
1. Update kf5-kwindowsystem:
```
sudo dnf install \
    https://copr-be.cloud.fedoraproject.org/results/zawertun/kde/fedora-30-x86_64/00973123-kf5-kwindowsystem/kf5-kwindowsystem-5.60.0-2.fc30.x86_64.rpm
```

2. Update kwin-lowlatency:
```
sudo dnf install \
    https://copr-be.cloud.fedoraproject.org/results/zawertun/kde/fedora-30-x86_64/00973218-kwin-lowlatency/kwin-lowlatency-5.16.3-2.fc30.x86_64.rpm \
    https://copr-be.cloud.fedoraproject.org/results/zawertun/kde/fedora-30-x86_64/00973218-kwin-lowlatency/kwin-lowlatency-common-5.16.3-2.fc30.x86_64.rpm \
    https://copr-be.cloud.fedoraproject.org/results/zawertun/kde/fedora-30-x86_64/00973218-kwin-lowlatency/kwin-lowlatency-libs-5.16.3-2.fc30.x86_64.rpm \
    https://copr-be.cloud.fedoraproject.org/results/zawertun/kde/fedora-30-x86_64/00973218-kwin-lowlatency/kwin-lowlatency-wayland-5.16.3-2.fc30.x86_64.rpm
```

**Comment by luminoso** [comment]
well.. it looks awesome

even firefox seems to respond well to "no title bar" settings now

![image](https://user-images.githubusercontent.com/296323/61393932-f1c2c380-a8b9-11e9-8c34-b0a53d34f67f.png)

**Comment by ZaWertun** [comment]
Commits: https://github.com/ZaWertun/fedora-copr-kde5/commit/f5073f337a3a1d5114f15c97b7a2baf196dbe988, https://github.com/ZaWertun/fedora-copr-kde5/commit/be5cecd253461a17b3523b095fc5f10251e6e8db.
