### ISSUE TITLE
Can't update "kig", broken requeriments

### ISSUE THREAD

**Issue by CarlosEkisde** [ZaWertun/fedora-copr-kde5#51]
Terminal output: 
cannot install the best update candidate for package kig-20.08.1-1.fc33.x86_64
  - nothing provides /usr/bin/python33 needed by kig-20.08.2-1.fc33.x86_64

**Comment by ZaWertun** [comment]
Fixed.

Commit: 9100bd8c01882abe0183c58e2022b6ea816e8335.
Build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1718002/.

**Comment by CarlosEkisde** [comment]
Thank you :+1:
