### ISSUE TITLE
kiogdrive issue

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#53]
Is anyone seeing this when launching kiogdrive from the shell or Dolphin

[g6avk@fbox ~]$ kioclient5 exec gdrive:/
kf.kio.core: couldn't create slave: "klauncher said: Error loading '/usr/lib64/qt5/plugins/kf5/kio/gdrive.so'."
kf.kio.widgets: KRun(0x55ca4a072e70) ERROR 173 "Unable to create io-slave. klauncher said: Error loading '/usr/lib64/qt5/plugins/kf5/kio/gdrive.so'."

I have had a quick look @kdebugs but have not found anything yet.

Fully updated F33

**Comment by ZaWertun** [comment]
I'll try to rebuild package with LTO disabled.

**Comment by ZaWertun** [comment]
I've got same crash on official Fedora package :(

**Comment by ZaWertun** [comment]
Rebuilding `libkgapi` without LTO support fixes the crash.
Wait for this build - https://copr.fedorainfracloud.org/coprs/build/1749785.

**Comment by g6avk** [comment]
OK I updated libkgapi  and ran "kioclient5 exec gdrive:/" and nothing is shown in the shell, Dolphin opens showing the local folder. 

But checking dmesg signon is crashing to the point it fills up dmesg and eats up CPU and I have to reboot :-( I'll try and do more bug hunting later today on bugzilla etc

**Comment by ZaWertun** [comment]
Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1895674.

**Comment by ZaWertun** [comment]
> OK I updated libkgapi and ran "kioclient5 exec gdrive:/" and nothing is shown in the shell, Dolphin opens showing the local folder.

I see account manager window when running `kioclient5 exec gdrive:/`:
![изображение](https://user-images.githubusercontent.com/1080298/98462583-5c41f600-21c6-11eb-816e-4a21d8754e81.png)

**Comment by g6avk** [comment]
> Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1895674.

Thanks, I'll add myself to that report.

**Comment by g6avk** [comment]
> > OK I updated libkgapi and ran "kioclient5 exec gdrive:/" and nothing is shown in the shell, Dolphin opens showing the local folder.
> 
> I see account manager window when running `kioclient5 exec gdrive:/`:
> ![изображение](https://user-images.githubusercontent.com/1080298/98462583-5c41f600-21c6-11eb-816e-4a21d8754e81.png)

I see the Dolphin screen but no account manager as I already have a Google Acc setup. Signon crashes trying to login I guess.

**Comment by ZaWertun** [comment]
> > > OK I updated libkgapi and ran "kioclient5 exec gdrive:/" and nothing is shown in the shell, Dolphin opens showing the local folder.
> > 
> > 
> > I see account manager window when running `kioclient5 exec gdrive:/`:
> > ![изображение](https://user-images.githubusercontent.com/1080298/98462583-5c41f600-21c6-11eb-816e-4a21d8754e81.png)
> 
> I see the Dolphin screen but no account manager as I already have a Google Acc setup. Signon crashes trying to login I guess.

I see this when trying to create new Google account:
![изображение](https://user-images.githubusercontent.com/1080298/98462874-711f8900-21c8-11eb-932d-ca14c4457c10.png)
Looks like some other bug.

**Comment by ZaWertun** [comment]
In the `gnome-abrt` I see info that `signond killed by SIGSEGV` (/usr/bin/signond).
Another crash caused by LTO? Huh.

**Comment by ZaWertun** [comment]
Just found about unability login to Google account: https://bugzilla.redhat.com/show_bug.cgi?id=1891251.
(Description of problem:
THe application crashes every time I try to add Google account. System Settings -> Online Accounts -> Add New Account  -> Google -> crash).

**Comment by g6avk** [comment]
> > > > OK I updated libkgapi and ran "kioclient5 exec gdrive:/" and nothing is shown in the shell, Dolphin opens showing the local folder.
> > > 
> > > 
> > > I see account manager window when running `kioclient5 exec gdrive:/`:
> > > ![изображение](https://user-images.githubusercontent.com/1080298/98462583-5c41f600-21c6-11eb-816e-4a21d8754e81.png)
> > 
> > 
> > I see the Dolphin screen but no account manager as I already have a Google Acc setup. Signon crashes trying to login I guess.
> 
> I see this when trying to create new Google account:
> ![изображение](https://user-images.githubusercontent.com/1080298/98462874-711f8900-21c8-11eb-932d-ca14c4457c10.png)
> Looks like some other bug.

Interesting.. I guess maybe signon is crashing as it cannot connect..

Maybe I'll try and add another account later and see if I get the remote disconnected warning.

**Comment by ZaWertun** [comment]
> Just found bug about unability login to Google account: https://bugzilla.redhat.com/show_bug.cgi?id=1891251.
> (Description of problem:
> THe application crashes every time I try to add Google account. System Settings -> Online Accounts -> Add New Account -> Google -> crash).

@g6avk ^^^

**Comment by g6avk** [comment]
> > Just found bug about unability login to Google account: https://bugzilla.redhat.com/show_bug.cgi?id=1891251.
> > (Description of problem:
> > THe application crashes every time I try to add Google account. System Settings -> Online Accounts -> Add New Account -> Google -> crash).
> 
> @g6avk ^^^

I cannot view that bug, access denied.. I have just found this, it seems many issues again with Google :-(

https://bugs.kde.org/show_bug.cgi?id=420280

**Comment by ZaWertun** [comment]
Just found cause of signond crash (https://bugzilla.redhat.com/show_bug.cgi?id=1891251).
Wait till it got fixed, there will be new build of `signon` package.

**Comment by g6avk** [comment]
> Just found cause of signond crash (https://bugzilla.redhat.com/show_bug.cgi?id=1891251).
> Wait till it got fixed, there will be new build of `signon` package.

Great!

 I cannot view that bug as I mentioned but look forward to the fix :)

**Comment by ZaWertun** [comment]
You can install this build of `signon`: https://koji.fedoraproject.org/koji/buildinfo?buildID=1639625.
It is not yet in the Fedora repository.

**Comment by g6avk** [comment]
> You can install this build of `signon`: https://koji.fedoraproject.org/koji/buildinfo?buildID=1639625.
> It is not yet in the Fedora repository.

Thanks, I just ran some tests and its looks good, no crashes, nothing in the logs. I will test more later..

When it appears in bodhi I can leave karma.

**Comment by ZaWertun** [comment]
There is update of `signon` for F33: https://bodhi.fedoraproject.org/updates/FEDORA-2020-d3daecdb08.

**Comment by g6avk** [comment]
> There is update of `signon` for F33: https://bodhi.fedoraproject.org/updates/FEDORA-2020-d3daecdb08.

OK, Karma left..
