### ISSUE TITLE
Plasma splashscreen is black in build 5.20.2-3

### ISSUE THREAD

**Issue by aleasto** [ZaWertun/fedora-copr-kde5#55]
Reverting to 5.20.2-1 works
`sudo dnf install plasma-workspace-5.20.2-1.fc33`

**Comment by ZaWertun** [comment]
> Reverting to 5.20.2-1 works
> `sudo dnf install plasma-workspace-5.20.2-1.fc33`

After first login or after logging out then logging in?

**Comment by aleasto** [comment]
> > Reverting to 5.20.2-1 works
> > `sudo dnf install plasma-workspace-5.20.2-1.fc33`
> 
> After first login or after logging out then logging in?

Definitly on first login.
Can't really say after logging out as logging out/relogging in has always been broken on my system :/

**Comment by ZaWertun** [comment]
Yep, I see black screen on login too. Thought that I've disabled splash screen.
Command `ksplashqml --test` works as expected - animation is shown.
No errors in log or crashes, I don't know where to dig yet.

**Comment by ZaWertun** [comment]
Something wrong with default splash screen.
I've installed QaurksSplashDark from store - works fine.

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1756455/

**Comment by aleasto** [comment]
Can confirm the opacity hack is working.
Another issue with the release is that login takes noticeably more time than on 50.2.3-1
I've started another issue for clarity #56
