### ISSUE TITLE
Login takes considerably more time on 5.20.2-[3-4]

### ISSUE THREAD

**Issue by aleasto** [ZaWertun/fedora-copr-kde5#56]
On my system, in release 5.20.2-1 and all prior builds the splashscreen flashes a couple of times before i'm sent very quickly to my Desktop.

Starting with 5.20.2-3 and continuing in the hotfix build 5.20.2-4, after the splashscreen flashes it keeps spinning for ~10 more seconds, effectively doubling if not tripling the time to login

**Comment by LithiumSR** [comment]
I can confirm. Default login screen stops spinning after a couple of seconds then It remains for ~10 more seconds before disappearing.

**Comment by architectlin** [comment]
I can confirm, with me the same problem

**Comment by ZaWertun** [comment]
It's not easy to debug such problems.
There is nice article from David Edmundson - http://blog.davidedmundson.co.uk/blog/plasma-startup/.

**Comment by architectlin** [comment]
> It's not easy to debug such problems.
> There is nice article from David Edmundson - http://blog.davidedmundson.co.uk/blog/plasma-startup/.

I know this was the same last time:'(

**Comment by ZaWertun** [comment]
I could make package that installs modified `systemd-bootchart` and adds script that runs it on X11 start.

**Comment by ZaWertun** [comment]
Damn. It caused by my patch, when I'm trying to fix dbus-broker issue.
New build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1767210/.

**Comment by ZaWertun** [comment]
But now after updating to 5.20.3 I have constant timeout before logging out (3-5 sec.).

**Comment by LithiumSR** [comment]
I can confirm that, after updating to the last build, the waiting time for logging in is back to normal. Thank you :+1:

**Comment by aleasto** [comment]
> But now after updating to 5.20.3 I have constant timeout before logging out (3-5 sec.).

Stable 5.20.3 is out.
Interestingly i have the same there.

**Comment by aleasto** [comment]
Oh well, I'll consider this fixed :)
