### ISSUE TITLE
Cannot log-in when upgrading plasma-workspace to 5.20.2-3.fc33

### ISSUE THREAD

**Issue by LittleJohn-dot** [ZaWertun/fedora-copr-kde5#57]
Hi,
Firstly thanks a lot for your hard work! But since the release of the 5.20.2-3.fc33 Plasma-workspace build whenever I try to log in it logs me back out. 
Today, I upgraded to 5.20.2-4.fc33, but the issue remains.

The only fix I found was to log in with GNOME and downgrade the package, along with its dependencies.

**Comment by ZaWertun** [comment]
Thanks!

Check journalctl for errors (or upload it there).
Or it could be same "old" bug: https://bugzilla.redhat.com/show_bug.cgi?id=1861700.

**Comment by LittleJohn-dot** [comment]
I only have one user, so I am not sure the issue correspond to mine.
So, I have checked through the journalctl logs, but I am not so good with the CLI. Currently checking with Gnome Logs, and I am seeing an error : 
`Service file '/usr/share/dbus-1/services/org.kde.kscreen.service' is not named after the D-Bus name 'org.kde.KScreen'.`
Could it be that ?

**Comment by ZaWertun** [comment]
> I only have one user, so I am not sure the issue correspond to mine.

It can be reproduced even with 1 user in the system (see comments).

> Service file '/usr/share/dbus-1/services/org.kde.kscreen.service' is not named after the D-Bus name 'org.kde.KScreen'.
> Could it be that ?

Try to rename service file to `org.kde.KScreen.service`, maybe it will help.

**Comment by ZaWertun** [comment]
I'll fix service file name in the package - better live without that warnings :)

**Comment by ZaWertun** [comment]
Warning should be fixed in `libkscreen-qt5-5.20.2-2.fc33`.

**Comment by LittleJohn-dot** [comment]
Could this error in ´libkscreen´ make the log in impossible? I will read through the bugzilla error report and seek if I can help you pinpoint the issue!

**Comment by ZaWertun** [comment]
> Could this error in ´libkscreen´ make the log in impossible? I will read through the bugzilla error report and seek if I can help you pinpoint the issue!

Probability of that is quite low, I see those warnings long ago and I don't have login problems (excluding RedHat bug 1861700 of course).
You can try creating new user & test login on fresh profile.

**Comment by ZaWertun** [comment]
Also check sddm log: `journalctl -u sddm`, maybe there are some errors in it.

**Comment by LittleJohn-dot** [comment]
`No entries` . I will upgrade `plasma-workspace`, reboot, and see if from GNOME I can give you something tangible.
So I went through the bugzilla bug report, and ran `journalctl | grep -i d-bus`, since it seems to be a lead. 
I now have entries about several services not named after D-Bus names. Would you like to have the output ?

**Comment by LittleJohn-dot** [comment]
I cannot make github process the file, here is the output, maybe it can help (Thanks for your patience) :
https://paste.rs/csE

**Comment by ZaWertun** [comment]
So you have GNOME installed in the parallel?
I'll try to reproduce this bug on my system.

P.S. Can you login after reboot?

**Comment by LittleJohn-dot** [comment]
Yes I kept GNOME, for no reasons actually. 
I cannot login after upgrading and rebooting, though, the `journalctl | grep -i sddm` command pointed me towards this : 
`... localhost.localdomain earlyoom[1266]: Will avoid killing process names that match regex '^(dnf|packagekitd|gnome-shell|gnome-session-c|gnome-session-b|lightdm|sddm|sddm-helper|gdm|gdm-wayland-ses|gdm-session-wor|gdm-x-session|Xorg|Xwayland|systemd|systemd-logind|dbus-daemon|dbus-broker|cinnamon|cinnamon-sessio|kwin_x11|kwin_wayland|plasmashell|ksmserver|plasma_session|startplasma-way|xfce4-session|mate-session|marco|lxqt-session|openbox)$'`

Could it be the cause of the issue? Coupled with the naming error I provided above? 
I hope you will be able to reproduce the bug, because I don't really know how to do to help you with this one.

**Comment by LittleJohn-dot** [comment]
Maybe the d-bus broker doesn't handle well when there are not capitals, and then earlyoom kills the processes that it shouldn't ?..

**Comment by ZaWertun** [comment]
> Maybe the d-bus broker doesn't handle well when there are no capitals, and then earlyoom kills the processes it shouldn't ?..

Don't know exactly, I've removed earlyoom. You can do the same if you have enough memory.

**Comment by LittleJohn-dot** [comment]
I don't know what you did but you did it right! Yesterday I updated plasma-workspace and now I was able to log in successfuly !! Thanks :)
