### ISSUE TITLE
Dolphin /usr/lib64/qt5/plugins/kf5/kio/file.so“

### ISSUE THREAD

**Issue by architectlin** [ZaWertun/fedora-copr-kde5#58]
Last update 

Open Dolphin Erstellung des Ein-/Ausgabemoduls nicht möglich. Meldung von klauncher: Fehler beim Laden von „/usr/lib64/qt5/plugins/kf5/kio/file.so“

**Comment by architectlin** [comment]
Forget reboot sorry

**Comment by ZaWertun** [comment]
To deal with such errors you can also start `kdeinit5` in the console - it should help without reboot.

**Comment by ZaWertun** [comment]
Yep. Just checked it - it helps.
