### ISSUE TITLE
KAddressbook import/export missing in 20.12

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#60]
Hi,
I cannot see the option in KAddressbook to import/export contacts, I notice kdepim-apps-libs is still @ 20.08 and wonder if this could be the issue?

dnf list --disablerepo=* | grep 20.08                         
kdepim-apps-libs.x86_64                          20.08.3-1.fc33                         @copr:copr.fedorainfracloud.org:zawertun:kde      
kf5-kipi-plugins.x86_64                          20.08.1-1.fc33                         @fedora

**Comment by ZaWertun** [comment]
Hi.
Maybe I forgot to update it. I'll check.

**Comment by ZaWertun** [comment]
`kdepim-addons` was built without `cmake(KPimAddressbookImportExport)` build dependency.
I fixed this: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1852927/.

Could you please add karma to new kio-fuse version? (https://bodhi.fedoraproject.org/updates/FEDORA-2021-8bf9233732).
It's the first stable release of kio-fuse.

**Comment by ZaWertun** [comment]
88fe1e2202a3da2e2c99113b0ff8744c50527d62

**Comment by g6avk** [comment]
Thanks installed and the menu options are back..

Fuse karma left :)

**Comment by g6avk** [comment]
Maybe closed this too early, sorry..
Question, with the new build of kdepim-addons do we remove kdepim-app-libs 20.08 now?

**Comment by ZaWertun** [comment]
Package `kdepim-app-libs` is not needed anymore.
I'll make `kdepim-runtime` obsolete it, it will be removed after submitting new build.

**Comment by ZaWertun** [comment]
Check again.

**Comment by g6avk** [comment]
Perfect!
Upgrading        : kdepim-runtime-libs-1:20.12.0-2.fc33.x86_64                                                                                               1/7 
Upgrading        : kdepim-runtime-1:20.12.0-2.fc33.x86_64 
Obsoleting       : kdepim-apps-libs-20.08.3-1.fc33.x86_64 

Thanks!
