### ISSUE TITLE
Set user Avatar login screen

### ISSUE THREAD

**Issue by architectlin** [ZaWertun/fedora-copr-kde5#63]
Set user Avatar  will not be displayed on login screen

**Comment by ZaWertun** [comment]
See this bug: https://bugs.kde.org/show_bug.cgi?id=422177.

**Comment by ZaWertun** [comment]
Quick fix:
```shell
ln -s /var/lib/AccountsService/icons/$USER ~/.face.icon
```

**Comment by ZaWertun** [comment]
Better solution.
Create file `/etc/sddm.conf.d/avatar.conf` with this content:
```ini
[Theme]
FacesDir=/var/lib/AccountsService/icons/
```
(found it here: https://wiki.archlinux.org/index.php/SDDM).

**Comment by architectlin** [comment]
> Better solution.
> Create file `/etc/sddm.conf.d/avatar.conf` with this content:
> 
> ```ini
> [Theme]
> FacesDir=/var/lib/AccountsService/icons/
> ```
> 
> (found it here: https://wiki.archlinux.org/index.php/SDDM).

this is not possible

**Comment by ZaWertun** [comment]
> > Better solution.
> > Create file `/etc/sddm.conf.d/avatar.conf` with this content:
> > ```ini
> > [Theme]
> > FacesDir=/var/lib/AccountsService/icons/
> > ```
> > 
> > 
> > (found it here: https://wiki.archlinux.org/index.php/SDDM).
> 
> this is not possible

Try this in the console:
```
sudo nano /etc/sddm.conf.d/avatar.conf
```
Then paste lines from above & save the file.

**Comment by architectlin** [comment]
I have made

**Comment by LithiumSR** [comment]
The issue is no longer reproducible after updating to Plasma 5.21, any change to the avatar is now applied correctly.
Maybe this issue can now be closed

**Comment by architectlin** [comment]
closed
