### ISSUE TITLE
Wrong path for polkit-kde-authentication-agent-1

### ISSUE THREAD

**Issue by luminoso** [ZaWertun/fedora-copr-kde5#66]
When running plasma session [services managed by systemd](http://blog.davidedmundson.co.uk/blog/plasma-and-the-systemd-startup/)

Plasma 5.21, Fedora 33 the `polkit-kde-5.21.0-1.fc33.x86_64`  systemd unit has the wrong path.

`/usr/lib/systemd/user/plasma-polkit-agent.service` is
```
[Unit]
Description=KDE PolicyKit Authentication Agent
PartOf=graphical-session.target
After=plasma-core.target

[Service]
ExecStart=/usr/libexec/polkit-kde-authentication-agent-1
BusName=org.kde.polkit-kde-authentication-agent-1
Slice=background.slice
TimeoutSec=5sec
Restart=on-failure
```
but `ExecStart=` should point to `/usr/libexec/kf5/polkit-kde-authentication-agent-1`, leading the service to fail.

This can be testing by enabling systemd-managed-session:

`kwriteconfig5 --file startkderc --group General --key systemdBoot true`

After fixing the path all services run and start perfectly.

P.S.: thank you so much for providing plasma 5.21 so fast!

**Comment by ZaWertun** [comment]
Uh oh, thanks for the report.

**Comment by ZaWertun** [comment]
Wait for this build to finish: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1976753/.
