### ISSUE TITLE
plasma 5.21 / kwin-lowlatency?

### ISSUE THREAD

**Issue by slartibart70** [ZaWertun/fedora-copr-kde5#68]
Hi,

could you please take a look at the dependencies of kwin-lowlatency (again)?
Current release 5.21 seems to work ok with standard kwin, but switching to kwin-lowlatency breaks dependencies.
Thanks !!

**Comment by ZaWertun** [comment]
Hi!
kwin-lowlatency still has no release for 5.21 version.
So better switch back to vanilla kwin for now.

**Comment by ZaWertun** [comment]
Corresponding discussion: https://github.com/tildearrow/kwin-lowlatency/issues/106.

**Comment by slartibart70** [comment]
Thanks!
(just read the corresponding discussion)
