### ISSUE TITLE
Can not install KWinFT 5.21

### ISSUE THREAD

**Issue by adarshahd** [ZaWertun/fedora-copr-kde5#69]
Not able to install KWinFT due to dependency issue.
```

Problem: package kwinft-5.21.0-1.fc33.x86_64 requires kwinft-common(x86-64) = 5.21.0-1.fc33, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides /usr/bin/python33 needed by kwinft-common-5.21.0-1.fc33.x86_64
```

**Comment by adarshahd** [comment]
Also sent a PR #70

**Comment by ZaWertun** [comment]
Should be fixed in this build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/2016564/.
(commit d53e2c6da499b436b53b588032c92bacf079bb8e).

**Comment by ZaWertun** [comment]
Looks like script `kwin-5.21-desktop-grid-click-behavior.py` won't be processed.
I'll make on more commit & new build.

**Comment by ZaWertun** [comment]
Commit: 1e2b4c043a5cbca7a373a20a8f45a99c1291b31b, build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/2016581/.

**Comment by adarshahd** [comment]
I can confirm, I am able to install KWinFT now. Thank you very much!
