### ISSUE TITLE
info.so from kio-extras conflicts with file from package kio-extras-info

### ISSUE THREAD

**Issue by tenten8401** [ZaWertun/fedora-copr-kde5#7]
Getting this error on a freshly updated system, trying to install from your copr repo the first time: Error: Transaction check error:
  file /usr/lib64/qt5/plugins/kf5/kio/info.so from install of kio-extras-19.04.3-1.fc30.x86_64 conflicts with file from package kio-extras-info-19.04.2-1.fc30.x86_64

Not sure where to start looking, but I think it might just be a packaging issue.

**Comment by ZaWertun** [comment]
It's just the same package, just higher version.
Never saw errors like that, looks like dnf bug.

**Comment by ZaWertun** [comment]
Dnf `must` update such packages.

**Comment by ZaWertun** [comment]
Do you have duplicate packages in your system?
You can check it with this command:
`dnf repoquery --duplicated --latest-limit -1 -q`

**Comment by tenten8401** [comment]
Ended up solving the issue by just removing `kio-extras-info`, pretty sure it's just a conflicting package.

**Comment by g6avk** [comment]
FYI to test I just tried to install kio-extras-info and dnf only picks up the package in fedora-updates not your repo, maybe a dnf issue ?

**Comment by ZaWertun** [comment]
Looks like some change in upstream package. I will sort this out.

**Comment by ZaWertun** [comment]
`kio-extras` was split to 2 packages.
I did not see it right away in the first message, sorry.
New build just submitted to copr: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/997565/.

**Comment by g6avk** [comment]
Yep, installs fine now.
