### ISSUE TITLE
Plasma 5.22

### ISSUE THREAD

**Issue by marco-calautti** [ZaWertun/fedora-copr-kde5#73]
With the new Plasma 5.22 out today, do you plan updating the copr with the latest version?

**Comment by ZaWertun** [comment]
Hello! New version has been built recently, just can't login into the Copr admin Web GUI.

**Comment by ZaWertun** [comment]
Ooops, sorry.
Actually I've built old version today 😀
Started building right now.

**Comment by marco-calautti** [comment]
It seems plasma-workspace 5.22 failed.

**Comment by ZaWertun** [comment]
New version already available in copr. Commit: cd032e5769a3a1a59d7a2ce6d6c9431738e85d1b.
