### ISSUE TITLE
plasma-discover-offline-updates should be removed

### ISSUE THREAD

**Issue by aleasto** [ZaWertun/fedora-copr-kde5#75]
There is a system setting toggle for offline updates now, that writes
```
[Software]
UseOfflineUpdates=true
```
in `~/.config/discoverrc` instead of the env variable

**Comment by ZaWertun** [comment]
System package can't change files in user home directories.
That's why such package as `plasma-discover-offline-updates` exists.

**Comment by aleasto** [comment]
It's not an install time toggle, but a runtime one.

You can try yourself in System Settings > Software Update

**Comment by ZaWertun** [comment]
This package is just changing system default.
There is no much sense removing it.
Plus it will be still available in Fedora repos => we'll get conflicts later.

**Comment by aleasto** [comment]
Currently the system settings toggle is ignored because the env variable takes precedence.
I'm pretty sure fedora is either going to remove this package or remove the toggle in system settings. This is bad UX.

**Comment by ZaWertun** [comment]
> Currently the system settings toggle is ignored because the env variable takes precedence.
> I'm pretty sure fedora is either going to remove this package or remove the toggle in system settings. This is bad UX.

I'll think it will be good to create issue about it on https://bugzilla.redhat.com/.
I myself not using Discover at all...

**Comment by ZaWertun** [comment]
Actually it more looks like KDE bug:
https://invent.kde.org/plasma/discover/-/blob/4e1617ae37b907836bc239b2507375c57f3b65c3/libdiscover/backends/PackageKitBackend/PackageKitUpdater.cpp#L380

**Comment by aleasto** [comment]
It's not a bug, it's the intended behaviour.

**Comment by ZaWertun** [comment]
So user can't disable offline updates if it was set by system?
Looks like bug to me.

**Comment by aleasto** [comment]
Because setting the env variable is not setting a "system default" but a "system override".
Perhaps KDE should offer a proper way for distros to change the default.

**Comment by aleasto** [comment]
Anyways i thought this was an addition thus i opened the issue.
I now see it's the same on Rawhide so i'll take it to fedora maintainers instead. Will keep open for updates.

**Comment by aleasto** [comment]
Fixed and merged already :)
https://src.fedoraproject.org/rpms/plasma-discover/c/2693d6e46421c7e6586840b5e978b9da3e9255b1?branch=rawhide

**Comment by ZaWertun** [comment]
> 
> 
> Fixed and merged already :)
> https://src.fedoraproject.org/rpms/plasma-discover/c/2693d6e46421c7e6586840b5e978b9da3e9255b1?branch=rawhide

Thanks! I'll merge those changes.

**Comment by ZaWertun** [comment]
Commit: 678d91d1f445b88edae3c1f9c8952c5591e3e49a.
Build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/2252926/.

**Comment by aleasto** [comment]
I can see the build completed, but dnf doesn't see it

**Comment by ZaWertun** [comment]
Manual metadata regeneration required. I've done it recently.

**Comment by aleasto** [comment]
Thanks, works
