### ISSUE TITLE
kinfocenter Plasma Version detection broken

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#76]
Just FYI

In Plasma 5.22.1 kinfocenter never reported the Plasma version. This still seems to be an issue with 5.22.2
Here is the bug report and fix:

https://bugs.kde.org/show_bug.cgi?id=436954

**Comment by ZaWertun** [comment]
Thanks for the info!
I took patches from official Fedora spec: 1f29144aa31560761538fa890a4fd3473e5e592d.
Should be fixed in new build kinfocenter-5.22.2.1-1.

**Comment by g6avk** [comment]
Yep confirmed fixed.

Thank you 👍🏻
