### ISSUE TITLE
PIM events plugin

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#77]
Hi,

Just FYI:
I noticed the PIM events plugin setting is missing in the Digital clock settings, here is the bug report and fix on kde.bugs

https://bugs.kde.org/show_bug.cgi?id=440449

**Comment by ZaWertun** [comment]
Patch applied: https://copr.fedorainfracloud.org/coprs/build/2522025.

**Comment by g6avk** [comment]
Thanks all is OK now
