### ISSUE TITLE
Missing package?

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#8]
Just installed 19.08 and ran into a slight issue and had to skip akonadiconsole for the update to work. DNF output below when trying to update akonadiconsole:

Cannot install the best update candidate for package akonadiconsole-19.04.3-1.fc30.x86_64
 - nothing provides akonadi-calendar-tools >= 19.08 needed by 
akonadiconsole-19.08.0-1.fc30.x86_64

**Comment by ZaWertun** [comment]
Yep. I've missed this package, thanks for feedback.
Just added it to copr: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1007200/.

**Comment by ZaWertun** [comment]
https://github.com/ZaWertun/fedora-copr-kde5/commit/fec1addb1995e7099e1d33b3c621550d4f0250ee

**Comment by g6avk** [comment]
That fixed it, akonadiconsole updated fine.
Thanks for your awesome COPR..
