### ISSUE TITLE
Kup e Bup

### ISSUE THREAD

**Issue by wagrod** [ZaWertun/fedora-copr-kde5#85]
Are there possibility to put the Kup and Bup in the repository? In the Fedora official repository there is not.

**Comment by ZaWertun** [comment]
Ooops, package `bup` in Fedora is is currently unmaintained...

**Comment by ZaWertun** [comment]
Done. You can try to install `kup` from my repo.

**Comment by wagrod** [comment]
Yes, I tried and ran very well. Thank you!
