### ISSUE TITLE
Unmet dependency for ktp-accounts-kcm (Fedora 35)

### ISSUE THREAD

**Issue by jose-matos** [ZaWertun/fedora-copr-kde5#86]
When installing packages in Fedora 35 there is a dependency that can not be satisfied:

```
 Problem 1: cannot install the best update candidate for package ktp-accounts-kcm-21.04.3-1.fc35.x86_64
  - nothing provides telepathy-rakia >= 0.7.4 needed by ktp-accounts-kcm-21.12.0-1.fc35.x86_64
```

The problem was already present with  ktp-accounts-kcm-21.08.1 and so it is not new in that sense.

Other than Fedora repos I have enabled rpmfusion but telepathy-rakia is not available in any of them.
According to https://src.fedoraproject.org/rpms/telepathy-rakia the package is orphaned since Fedora 33 and so probably the dependency can be dropped.

Thank you. :-)

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/build/3118878

**Comment by ZaWertun** [comment]
New build is ready.

**Comment by jose-matos** [comment]
Thank you.
I confirm that it works and now the upgrade path is clean with all the dependencies working correctly.
