### ISSUE TITLE
Package KTorrent 

### ISSUE THREAD

**Issue by kah0922** [ZaWertun/fedora-copr-kde5#88]
KTorrent is part of the KDE Gear application set yet is noticeably absent from this repo. Would it be possible to package it? ktorrent-libs would also need to be packaged.

**Comment by ZaWertun** [comment]
Sure, no  problem.

**Comment by ZaWertun** [comment]
+ kf5-libktorrent build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/3159722/
+ ktorrent build: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/3159738/

**Comment by ZaWertun** [comment]
Fixed building on Fedora 34: https://copr.fedorainfracloud.org/coprs/build/3159792

**Comment by kah0922** [comment]
Seems like it works fine to me, so I'll close this.
