### ISSUE TITLE
Skanpage

### ISSUE THREAD

**Issue by marco-calautti** [ZaWertun/fedora-copr-kde5#89]
Hi, there is a recent app from kde for scanning documents. It is called skanpage: https://apps.kde.org/skanpage/

Could you please add it to the repo?

Thanks

**Comment by ZaWertun** [comment]
Also skanlite was added in commit 07c322f15c9a7eb5f9cf2334faa6ea1eeebc8f89.

**Comment by ZaWertun** [comment]
Builds:
+ skanlite - https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/3777553/
+ skanpage - https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/3777566/
