### ISSUE TITLE
plasma-vault & plasma-workspace-wallpapers is missing

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#9]
FYI
Not an issue, but I noticed on my F30 system plasma-vault and 
plasma-workspace-wallpapers are previous versions.

**Comment by ZaWertun** [comment]
d4a182029350c03e94bb4508718cb9b480030afe

**Comment by ZaWertun** [comment]
Builds (version 5.16.5):
plasma-vault: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1038371/
plasma-workspace-wallpapers: https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/1038378/

**Comment by g6avk** [comment]
Both Updated and installed fine.. Thank you.
