### ISSUE TITLE
Repo Metadata didn't update after latest (5.24.0) build

### ISSUE THREAD

**Issue by mmcnutt** [ZaWertun/fedora-copr-kde5#92]
Hey just a heads up that the repo metadata didnt get updated after your last set of builds. I'm not intimately familiar with copr but the correct metadata still resides in https://download.copr.fedorainfracloud.org/results/zawertun/kde/fedora-35-x86_64/devel/repodata/
I copied those files into my /var/cache/dnf/copr:copr.fedorainfracloud.org:zawertun:kde-4c967a4d1a7620e4/repodata folder and was able to correctly install the latest build. Just https://download.copr.fedorainfracloud.org/results/zawertun/kde/fedora-35-x86_64/repodata/ was not updated by the copr system

perhaps a transient issue on the copr build service?

**Comment by ZaWertun** [comment]
Hi.
I try to do metadata update one more time.

**Comment by ZaWertun** [comment]
Done, you could try again after 5-10 min.

**Comment by g6avk** [comment]
Just updated my F35 box with no problems.. Many thanks for the updates 👍🏻

**Comment by mmcnutt** [comment]
yep querying the repo finds the packages now, thanks
