### ISSUE TITLE
FYI - Infocenter: Graphics: The executable $command could not be found in $PATH

### ISSUE THREAD

**Issue by g6avk** [ZaWertun/fedora-copr-kde5#96]
I just stumbled across this whilst looking through info center, click the graphics tab and you will see $command could not be found in $PATH and some sections. I had to install vulkan-tools, egl-utils and wayland-utils. Now all is good. Bug report : 

https://bugs.kde.org/show_bug.cgi?id=448706

**Comment by ZaWertun** [comment]
It's already fixed in 46c593a09873dab483dcd2d66081d1884f5e1fb6.
But I need to double check that new build includes those changes.
